version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.NAV_READ_PACKAGES }}
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 30
    registries: "*"
    groups:
      minor-and-patch-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
      major-dependencies:
        patterns:
          - '*'
        update-types:
          - 'major'
  - package-ecosystem: "docker"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10