version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.NAV_READ_PACKAGES }}
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 15
    registries: "*"
    ignore:
      - dependency-name: "snyk" # kommer så ofte. oppdateres med yarn outdated og yarn upgrade
      - dependency-name: "@navikt/ds-css" # ds-pakkene må følge versjonen i familie-felles-frontend
      - dependency-name: "@navikt/ds-css-internal"
      - dependency-name: "@navikt/ds-icons"
      - dependency-name: "@navikt/ds-react"
      - dependency-name: "@navikt/ds-react-internal"
      - dependency-name: "@navikt/ds-tokens"
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      minor-and-patch-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: "docker"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday"
