version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.NAV_READ_PACKAGES }}
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 15
    registries: "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      sentry:
        patterns:
          - "@sentry/core"
          - "@sentry/browser"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
      react:
        patterns:
          - "react"
          - "@types/react"
          - "react-dom"
          - "@types/react-dom"
      aksel:
        patterns:
          - "@navikt/aksel-icons"
          - "@navikt/ds-*"
        exclude-patterns:
          - "@navikt/ds-icons"
  - package-ecosystem: "docker"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10