version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday"
