// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
    BehandlingBehandlingsloggData,
    BehandlingBehandlingsloggErrors,
    BehandlingBehandlingsloggResponses,
    BehandlingFaktaData,
    BehandlingFaktaErrors,
    BehandlingFaktaResponses,
    BehandlingForeslaaVedtakData,
    BehandlingForeslaaVedtakErrors,
    BehandlingForeslaaVedtakResponses,
    BehandlingForhandsvarselData,
    BehandlingForhandsvarselErrors,
    BehandlingForhandsvarselResponses,
    BehandlingHentVedtaksbrevData,
    BehandlingHentVedtaksbrevErrors,
    BehandlingHentVedtaksbrevResponses,
    BehandlingHentVedtaksresultatData,
    BehandlingHentVedtaksresultatErrors,
    BehandlingHentVedtaksresultatResponses,
    BehandlingLagreBrukersuttalelseData,
    BehandlingLagreBrukersuttalelseErrors,
    BehandlingLagreBrukersuttalelseResponses,
    BehandlingLagreForhaandsvarselUnntakData,
    BehandlingLagreForhaandsvarselUnntakErrors,
    BehandlingLagreForhaandsvarselUnntakResponses,
    BehandlingOppdaterFaktaData,
    BehandlingOppdaterFaktaErrors,
    BehandlingOppdaterFaktaResponses,
    BehandlingOppdaterVedtaksbrevData,
    BehandlingOppdaterVedtaksbrevErrors,
    BehandlingOppdaterVedtaksbrevResponses,
    BehandlingSendVarselbrevData,
    BehandlingSendVarselbrevErrors,
    BehandlingSendVarselbrevResponses,
    BehandlingUtsettUttalelsesfristData,
    BehandlingUtsettUttalelsesfristErrors,
    BehandlingUtsettUttalelsesfristResponses,
    VedtaksbrevLagSvgVedtaksbrevData,
    VedtaksbrevLagSvgVedtaksbrevResponses,
} from './types.gen';

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const behandlingBehandlingslogg = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingBehandlingsloggData, ThrowOnError>
) =>
    (options.client ?? client).get<
        BehandlingBehandlingsloggResponses,
        BehandlingBehandlingsloggErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/behandlingslogg',
        ...options,
    });

export const behandlingFakta = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingFaktaData, ThrowOnError>
) =>
    (options.client ?? client).get<BehandlingFaktaResponses, BehandlingFaktaErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/feilutbetaling',
        ...options,
    });

export const behandlingOppdaterFakta = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingOppdaterFaktaData, ThrowOnError>
) =>
    (options.client ?? client).patch<
        BehandlingOppdaterFaktaResponses,
        BehandlingOppdaterFaktaErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/feilutbetaling',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const behandlingForeslaaVedtak = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingForeslaaVedtakData, ThrowOnError>
) =>
    (options.client ?? client).post<
        BehandlingForeslaaVedtakResponses,
        BehandlingForeslaaVedtakErrors,
        ThrowOnError
    >({ url: '/api/v1/behandling/{behandlingId}/foreslå-vedtak', ...options });

export const behandlingForhandsvarsel = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingForhandsvarselData, ThrowOnError>
) =>
    (options.client ?? client).get<
        BehandlingForhandsvarselResponses,
        BehandlingForhandsvarselErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel',
        ...options,
    });

export const behandlingSendVarselbrev = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingSendVarselbrevData, ThrowOnError>
) =>
    (options.client ?? client).post<
        BehandlingSendVarselbrevResponses,
        BehandlingSendVarselbrevErrors,
        ThrowOnError
    >({
        url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel/send-varselbrev',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const behandlingLagreForhaandsvarselUnntak = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingLagreForhaandsvarselUnntakData, ThrowOnError>
) =>
    (options.client ?? client).post<
        BehandlingLagreForhaandsvarselUnntakResponses,
        BehandlingLagreForhaandsvarselUnntakErrors,
        ThrowOnError
    >({
        url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel/unntak',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const behandlingUtsettUttalelsesfrist = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingUtsettUttalelsesfristData, ThrowOnError>
) =>
    (options.client ?? client).put<
        BehandlingUtsettUttalelsesfristResponses,
        BehandlingUtsettUttalelsesfristErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel/utsett-frist',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const behandlingLagreBrukersuttalelse = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingLagreBrukersuttalelseData, ThrowOnError>
) =>
    (options.client ?? client).post<
        BehandlingLagreBrukersuttalelseResponses,
        BehandlingLagreBrukersuttalelseErrors,
        ThrowOnError
    >({
        url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel/uttalelse',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const behandlingHentVedtaksbrev = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingHentVedtaksbrevData, ThrowOnError>
) =>
    (options.client ?? client).get<
        BehandlingHentVedtaksbrevResponses,
        BehandlingHentVedtaksbrevErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/vedtak/brev',
        ...options,
    });

export const behandlingOppdaterVedtaksbrev = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingOppdaterVedtaksbrevData, ThrowOnError>
) =>
    (options.client ?? client).put<
        BehandlingOppdaterVedtaksbrevResponses,
        BehandlingOppdaterVedtaksbrevErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/vedtak/brev',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const behandlingHentVedtaksresultat = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingHentVedtaksresultatData, ThrowOnError>
) =>
    (options.client ?? client).get<
        BehandlingHentVedtaksresultatResponses,
        BehandlingHentVedtaksresultatErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/vedtak/resultat',
        ...options,
    });

export const vedtaksbrevLagSvgVedtaksbrev = <ThrowOnError extends boolean = false>(
    options: Options<VedtaksbrevLagSvgVedtaksbrevData, ThrowOnError>
) =>
    (options.client ?? client).post<VedtaksbrevLagSvgVedtaksbrevResponses, unknown, ThrowOnError>({
        responseType: 'blob',
        url: '/api/v1/brev/vedtaksbrev/svg',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });
