// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
    BehandlingFaktaData,
    BehandlingFaktaErrors,
    BehandlingFaktaResponses,
    BehandlingHentVedtaksbrevData,
    BehandlingHentVedtaksbrevErrors,
    BehandlingHentVedtaksbrevResponses,
    BehandlingOppdaterFaktaData,
    BehandlingOppdaterFaktaErrors,
    BehandlingOppdaterFaktaResponses,
    VedtaksbrevLagSvgVedtaksbrevData,
    VedtaksbrevLagSvgVedtaksbrevResponses,
} from './types.gen';

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const behandlingFakta = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingFaktaData, ThrowOnError>
) =>
    (options.client ?? client).get<BehandlingFaktaResponses, BehandlingFaktaErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/feilutbetaling',
        ...options,
    });

export const behandlingOppdaterFakta = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingOppdaterFaktaData, ThrowOnError>
) =>
    (options.client ?? client).patch<
        BehandlingOppdaterFaktaResponses,
        BehandlingOppdaterFaktaErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/feilutbetaling',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const behandlingHentVedtaksbrev = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingHentVedtaksbrevData, ThrowOnError>
) =>
    (options.client ?? client).get<
        BehandlingHentVedtaksbrevResponses,
        BehandlingHentVedtaksbrevErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/vedtak/brev',
        ...options,
    });

export const vedtaksbrevLagSvgVedtaksbrev = <ThrowOnError extends boolean = false>(
    options: Options<VedtaksbrevLagSvgVedtaksbrevData, ThrowOnError>
) =>
    (options.client ?? client).post<VedtaksbrevLagSvgVedtaksbrevResponses, unknown, ThrowOnError>({
        responseType: 'blob',
        url: '/api/v1/brev/vedtaksbrev/svg',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });
