// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type {
    BehandlingBehandlingsloggData,
    BehandlingBehandlingsloggErrors,
    BehandlingBehandlingsloggResponses,
    BehandlingFaktaData,
    BehandlingFaktaErrors,
    BehandlingFaktaResponses,
    BehandlingForeslaaVedtakData,
    BehandlingForeslaaVedtakErrors,
    BehandlingForeslaaVedtakResponses,
    BehandlingForhandsvarselData,
    BehandlingForhandsvarselErrors,
    BehandlingForhandsvarselResponses,
    BehandlingHentDokumentData,
    BehandlingHentDokumentErrors,
    BehandlingHentDokumentInfoData,
    BehandlingHentDokumentInfoErrors,
    BehandlingHentDokumentInfoResponses,
    BehandlingHentDokumentResponses,
    BehandlingHentVedtaksbrevData,
    BehandlingHentVedtaksbrevErrors,
    BehandlingHentVedtaksbrevResponses,
    BehandlingHentVedtaksresultatData,
    BehandlingHentVedtaksresultatErrors,
    BehandlingHentVedtaksresultatResponses,
    BehandlingLagreBrukersuttalelseData,
    BehandlingLagreBrukersuttalelseErrors,
    BehandlingLagreBrukersuttalelseResponses,
    BehandlingLagreForhaandsvarselUnntakData,
    BehandlingLagreForhaandsvarselUnntakErrors,
    BehandlingLagreForhaandsvarselUnntakResponses,
    BehandlingLagreVilkaarsvurderingData,
    BehandlingLagreVilkaarsvurderingErrors,
    BehandlingLagreVilkaarsvurderingResponses,
    BehandlingOppdaterFaktaData,
    BehandlingOppdaterFaktaErrors,
    BehandlingOppdaterFaktaResponses,
    BehandlingOppdaterVedtaksbrevData,
    BehandlingOppdaterVedtaksbrevErrors,
    BehandlingOppdaterVedtaksbrevResponses,
    BehandlingSendVarselbrevData,
    BehandlingSendVarselbrevErrors,
    BehandlingSendVarselbrevResponses,
    BehandlingSlaaSammenPerioderData,
    BehandlingSlaaSammenPerioderErrors,
    BehandlingSlaaSammenPerioderResponses,
    BehandlingSplittPeriodeData,
    BehandlingSplittPeriodeErrors,
    BehandlingSplittPeriodeResponses,
    BehandlingUtsettUttalelsesfristData,
    BehandlingUtsettUttalelsesfristErrors,
    BehandlingUtsettUttalelsesfristResponses,
    BehandlingVilkaarsvurderingData,
    BehandlingVilkaarsvurderingErrors,
    BehandlingVilkaarsvurderingResponses,
    BehandlingVilkaarsvurderingsperioderData,
    BehandlingVilkaarsvurderingsperioderErrors,
    BehandlingVilkaarsvurderingsperioderResponses,
    VedtaksbrevLagSvgVedtaksbrevData,
    VedtaksbrevLagSvgVedtaksbrevResponses,
} from './types.gen';

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const behandlingBehandlingslogg = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingBehandlingsloggData, ThrowOnError>
): RequestResult<
    BehandlingBehandlingsloggResponses,
    BehandlingBehandlingsloggErrors,
    ThrowOnError
> =>
    (options.client ?? client).get<
        BehandlingBehandlingsloggResponses,
        BehandlingBehandlingsloggErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/behandlingslogg',
        ...options,
    });

export const behandlingFakta = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingFaktaData, ThrowOnError>
): RequestResult<BehandlingFaktaResponses, BehandlingFaktaErrors, ThrowOnError> =>
    (options.client ?? client).get<BehandlingFaktaResponses, BehandlingFaktaErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/feilutbetaling',
        ...options,
    });

export const behandlingOppdaterFakta = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingOppdaterFaktaData, ThrowOnError>
): RequestResult<BehandlingOppdaterFaktaResponses, BehandlingOppdaterFaktaErrors, ThrowOnError> =>
    (options.client ?? client).patch<
        BehandlingOppdaterFaktaResponses,
        BehandlingOppdaterFaktaErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/feilutbetaling',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const behandlingForeslaaVedtak = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingForeslaaVedtakData, ThrowOnError>
): RequestResult<BehandlingForeslaaVedtakResponses, BehandlingForeslaaVedtakErrors, ThrowOnError> =>
    (options.client ?? client).post<
        BehandlingForeslaaVedtakResponses,
        BehandlingForeslaaVedtakErrors,
        ThrowOnError
    >({ url: '/api/v1/behandling/{behandlingId}/foreslå-vedtak', ...options });

export const behandlingForhandsvarsel = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingForhandsvarselData, ThrowOnError>
): RequestResult<BehandlingForhandsvarselResponses, BehandlingForhandsvarselErrors, ThrowOnError> =>
    (options.client ?? client).get<
        BehandlingForhandsvarselResponses,
        BehandlingForhandsvarselErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel',
        ...options,
    });

export const behandlingSendVarselbrev = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingSendVarselbrevData, ThrowOnError>
): RequestResult<BehandlingSendVarselbrevResponses, BehandlingSendVarselbrevErrors, ThrowOnError> =>
    (options.client ?? client).post<
        BehandlingSendVarselbrevResponses,
        BehandlingSendVarselbrevErrors,
        ThrowOnError
    >({
        url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel/send-varselbrev',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const behandlingLagreForhaandsvarselUnntak = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingLagreForhaandsvarselUnntakData, ThrowOnError>
): RequestResult<
    BehandlingLagreForhaandsvarselUnntakResponses,
    BehandlingLagreForhaandsvarselUnntakErrors,
    ThrowOnError
> =>
    (options.client ?? client).post<
        BehandlingLagreForhaandsvarselUnntakResponses,
        BehandlingLagreForhaandsvarselUnntakErrors,
        ThrowOnError
    >({
        url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel/unntak',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const behandlingUtsettUttalelsesfrist = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingUtsettUttalelsesfristData, ThrowOnError>
): RequestResult<
    BehandlingUtsettUttalelsesfristResponses,
    BehandlingUtsettUttalelsesfristErrors,
    ThrowOnError
> =>
    (options.client ?? client).put<
        BehandlingUtsettUttalelsesfristResponses,
        BehandlingUtsettUttalelsesfristErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel/utsett-frist',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const behandlingLagreBrukersuttalelse = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingLagreBrukersuttalelseData, ThrowOnError>
): RequestResult<
    BehandlingLagreBrukersuttalelseResponses,
    BehandlingLagreBrukersuttalelseErrors,
    ThrowOnError
> =>
    (options.client ?? client).post<
        BehandlingLagreBrukersuttalelseResponses,
        BehandlingLagreBrukersuttalelseErrors,
        ThrowOnError
    >({
        url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel/uttalelse',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const behandlingHentDokument = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingHentDokumentData, ThrowOnError>
): RequestResult<BehandlingHentDokumentResponses, BehandlingHentDokumentErrors, ThrowOnError> =>
    (options.client ?? client).get<
        BehandlingHentDokumentResponses,
        BehandlingHentDokumentErrors,
        ThrowOnError
    >({
        responseType: 'blob',
        url: '/api/v1/behandling/{behandlingId}/journalpost/{journalpostId}/dokument/{dokumentInfoId}',
        ...options,
    });

export const behandlingHentVedtaksbrev = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingHentVedtaksbrevData, ThrowOnError>
): RequestResult<
    BehandlingHentVedtaksbrevResponses,
    BehandlingHentVedtaksbrevErrors,
    ThrowOnError
> =>
    (options.client ?? client).get<
        BehandlingHentVedtaksbrevResponses,
        BehandlingHentVedtaksbrevErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/vedtak/brev',
        ...options,
    });

export const behandlingOppdaterVedtaksbrev = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingOppdaterVedtaksbrevData, ThrowOnError>
): RequestResult<
    BehandlingOppdaterVedtaksbrevResponses,
    BehandlingOppdaterVedtaksbrevErrors,
    ThrowOnError
> =>
    (options.client ?? client).put<
        BehandlingOppdaterVedtaksbrevResponses,
        BehandlingOppdaterVedtaksbrevErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/vedtak/brev',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const behandlingHentVedtaksresultat = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingHentVedtaksresultatData, ThrowOnError>
): RequestResult<
    BehandlingHentVedtaksresultatResponses,
    BehandlingHentVedtaksresultatErrors,
    ThrowOnError
> =>
    (options.client ?? client).get<
        BehandlingHentVedtaksresultatResponses,
        BehandlingHentVedtaksresultatErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/vedtak/resultat',
        ...options,
    });

export const behandlingVilkaarsvurdering = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingVilkaarsvurderingData, ThrowOnError>
): RequestResult<
    BehandlingVilkaarsvurderingResponses,
    BehandlingVilkaarsvurderingErrors,
    ThrowOnError
> =>
    (options.client ?? client).get<
        BehandlingVilkaarsvurderingResponses,
        BehandlingVilkaarsvurderingErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/vilkårsvurdering',
        ...options,
    });

export const behandlingLagreVilkaarsvurdering = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingLagreVilkaarsvurderingData, ThrowOnError>
): RequestResult<
    BehandlingLagreVilkaarsvurderingResponses,
    BehandlingLagreVilkaarsvurderingErrors,
    ThrowOnError
> =>
    (options.client ?? client).post<
        BehandlingLagreVilkaarsvurderingResponses,
        BehandlingLagreVilkaarsvurderingErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/vilkårsvurdering',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const behandlingVilkaarsvurderingsperioder = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingVilkaarsvurderingsperioderData, ThrowOnError>
): RequestResult<
    BehandlingVilkaarsvurderingsperioderResponses,
    BehandlingVilkaarsvurderingsperioderErrors,
    ThrowOnError
> =>
    (options.client ?? client).get<
        BehandlingVilkaarsvurderingsperioderResponses,
        BehandlingVilkaarsvurderingsperioderErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/vilkårsvurdering/perioder',
        ...options,
    });

export const behandlingSlaaSammenPerioder = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingSlaaSammenPerioderData, ThrowOnError>
): RequestResult<
    BehandlingSlaaSammenPerioderResponses,
    BehandlingSlaaSammenPerioderErrors,
    ThrowOnError
> =>
    (options.client ?? client).post<
        BehandlingSlaaSammenPerioderResponses,
        BehandlingSlaaSammenPerioderErrors,
        ThrowOnError
    >({
        url: '/api/v1/behandling/{behandlingId}/vilkårsvurdering/sammenslå',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const behandlingSplittPeriode = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingSplittPeriodeData, ThrowOnError>
): RequestResult<BehandlingSplittPeriodeResponses, BehandlingSplittPeriodeErrors, ThrowOnError> =>
    (options.client ?? client).post<
        BehandlingSplittPeriodeResponses,
        BehandlingSplittPeriodeErrors,
        ThrowOnError
    >({
        url: '/api/v1/behandling/{behandlingId}/vilkårsvurdering/splitt',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const behandlingHentDokumentInfo = <ThrowOnError extends boolean = false>(
    options: Options<BehandlingHentDokumentInfoData, ThrowOnError>
): RequestResult<
    BehandlingHentDokumentInfoResponses,
    BehandlingHentDokumentInfoErrors,
    ThrowOnError
> =>
    (options.client ?? client).get<
        BehandlingHentDokumentInfoResponses,
        BehandlingHentDokumentInfoErrors,
        ThrowOnError
    >({
        responseType: 'json',
        url: '/api/v1/behandling/{behandlingId}/{dokumentType}/gjeldende',
        ...options,
    });

export const vedtaksbrevLagSvgVedtaksbrev = <ThrowOnError extends boolean = false>(
    options: Options<VedtaksbrevLagSvgVedtaksbrevData, ThrowOnError>
): RequestResult<VedtaksbrevLagSvgVedtaksbrevResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<VedtaksbrevLagSvgVedtaksbrevResponses, unknown, ThrowOnError>({
        responseType: 'blob',
        url: '/api/v1/brev/vedtaksbrev/svg',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });
