// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://raw.githubusercontent.com' | (string & {});
};

export type Avsnitt = {
    tittel: string;
    readonly forklaring: string;
    id: string;
    underavsnitt: Array<RotElement>;
};

export type AvsnittUpdateItem = {
    tittel: string;
    id: string;
    underavsnitt: Array<RotElementUpdateItem>;
};

export type Beregningsresultat = {
    beregningsresultatsperioder: Array<Beregningsresultatsperiode>;
    vedtaksresultat: Vedtaksresultat;
};

export type BeregningsresultatVurdering =
    | 'GodTro'
    | 'Forsett'
    | 'SimpelUaktsomhet'
    | 'GrovUaktsomhet';

export type Beregningsresultatsperiode = {
    fom: string;
    tom: string;
    feilutbetaltBeløp: number;
    vurdering: BeregningsresultatVurdering;
    andelAvBeløp: number;
    renteprosent: number;
    tilbakekrevingsbeløp: number;
    tilbakekrevesBeløpEtterSkatt: number;
};

export type BestemmelseEllerGrunnlag = {
    nøkkel: string;
    beskrivelse: string;
};

export type Brevmottaker = {
    navn: string;
    personIdent: string;
};

export type Element = {
    type: 'rentekst';
} & RentekstElement;

export type Error = {
    message: string;
};

export type FaktaOmFeilutbetaling = {
    feilutbetaling: Feilutbetaling;
    tidligereVarsletBeløp: number | null;
    muligeRettsligGrunnlag: Array<MuligeRettsligGrunnlag>;
    perioder: Array<FaktaPeriode>;
    vurdering: Vurdering;
    ferdigvurdert: boolean;
};

export type FaktaPeriode = {
    id: string;
    fom: string;
    tom: string;
    feilutbetaltBeløp: number;
    splittbarePerioder: Array<{
        id: string;
        fom: string;
        tom: string;
        feilutbetaltBeløp: number;
        rettsligGrunnlag: Array<RettsligGrunnlag>;
    }>;
    rettsligGrunnlag: Array<RettsligGrunnlag>;
};

export type Feilutbetaling = {
    beløp: number;
    fom: string;
    tom: string;
    revurdering: Revurdering;
};

export type Fritekst = string;

export type Hovedavsnitt = {
    tittel: string;
    readonly forklaring: string;
    underavsnitt: Array<RotElement>;
};

export type HovedavsnittUpdate = {
    tittel: string;
    underavsnitt: Array<RotElementUpdateItem>;
};

export type MuligeRettsligGrunnlag = {
    bestemmelse: BestemmelseEllerGrunnlag;
    grunnlag: Array<BestemmelseEllerGrunnlag>;
};

export type Oppdaget = {
    dato: string | null;
    av: AvEnum;
    beskrivelse: Fritekst | null;
};

export type OppdaterFaktaOmFeilutbetaling = {
    perioder?: Array<OppdaterFaktaPeriode>;
    vurdering?: Vurdering;
};

export type OppdaterFaktaPeriode = {
    id: string;
    rettsligGrunnlag: Array<RettsligGrunnlag>;
};

export type PakrevdBegrunnelse = {
    tittel: string;
    readonly forklaring: string;
    begrunnelseType: string;
    underavsnitt: Array<Element>;
};

export type PakrevdBegrunnelseUpdateItem = {
    begrunnelseType: string;
    underavsnitt: Array<Element>;
};

export type RentekstElement = {
    tekst: string;
};

export type RettsligGrunnlag = {
    bestemmelse: string;
    grunnlag: string;
};

export type Revurdering = {
    årsak: string;
    vedtaksdato: string;
    resultat: ResultatEnum;
};

export type RotElement =
    | ({
          type: 'rentekst';
      } & RentekstElement)
    | ({
          type: 'underavsnitt';
      } & UnderavsnittElement)
    | ({
          type: 'påkrevd_begrunnelse';
      } & PakrevdBegrunnelse);

export type RotElementUpdateItem =
    | ({
          type: 'rentekst';
      } & RentekstElement)
    | ({
          type: 'underavsnitt';
      } & UnderavsnittElement)
    | ({
          type: 'påkrevd_begrunnelse';
      } & PakrevdBegrunnelseUpdateItem);

export type Signatur = {
    enhetNavn: string;
    ansvarligSaksbehandler: string;
    besluttendeSaksbehandler: string | null;
};

export type UnderavsnittElement = {
    tittel: string;
    underavsnitt: Array<Element>;
};

export type VedtaksbrevData = {
    hovedavsnitt: Hovedavsnitt;
    avsnitt: Array<Avsnitt>;
    readonly sistOppdatert: string;
    brevGjelder: Brevmottaker;
    sendtDato: string;
    ytelse: Ytelse;
    signatur: Signatur;
};

export type VedtaksbrevRedigerbareData = {
    hovedavsnitt: Hovedavsnitt;
    avsnitt: Array<Avsnitt>;
    readonly sistOppdatert: string;
};

export type VedtaksbrevRedigerbareDataUpdate = {
    hovedavsnitt: HovedavsnittUpdate;
    avsnitt: Array<AvsnittUpdateItem>;
};

export type Vedtaksresultat =
    | 'IngenTilbakebetaling'
    | 'DelvisTilbakebetaling'
    | 'FullTilbakebetaling';

export type Vurdering = {
    årsak: Fritekst | null;
    oppdaget?: Oppdaget;
};

export type Ytelse = {
    url: string;
    ubestemtEntall: string;
    bestemtEntall: string;
};

export type AvEnum = 'NAV' | 'BRUKER' | 'IKKE_VURDERT';

export type ResultatEnum = 'INNVILGET' | 'OPPHØRT';

export type AvsnittWritable = {
    tittel: string;
    id: string;
    underavsnitt: Array<RotElementWritable>;
};

export type HovedavsnittWritable = {
    tittel: string;
    underavsnitt: Array<RotElementWritable>;
};

export type PakrevdBegrunnelseWritable = {
    tittel: string;
    begrunnelseType: string;
    underavsnitt: Array<Element>;
};

export type RotElementWritable =
    | ({
          type: 'rentekst';
      } & RentekstElement)
    | ({
          type: 'underavsnitt';
      } & UnderavsnittElement)
    | ({
          type: 'påkrevd_begrunnelse';
      } & PakrevdBegrunnelseWritable);

export type VedtaksbrevDataWritable = {
    hovedavsnitt: HovedavsnittWritable;
    avsnitt: Array<AvsnittWritable>;
    brevGjelder: Brevmottaker;
    sendtDato: string;
    ytelse: Ytelse;
    signatur: Signatur;
};

export type VedtaksbrevRedigerbareDataWritable = {
    hovedavsnitt: HovedavsnittWritable;
    avsnitt: Array<AvsnittWritable>;
};

export type BehandlingFaktaData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/feilutbetaling';
};

export type BehandlingFaktaErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingFaktaError = BehandlingFaktaErrors[keyof BehandlingFaktaErrors];

export type BehandlingFaktaResponses = {
    /**
     * The request has succeeded.
     */
    200: FaktaOmFeilutbetaling;
};

export type BehandlingFaktaResponse = BehandlingFaktaResponses[keyof BehandlingFaktaResponses];

export type BehandlingOppdaterFaktaData = {
    body: OppdaterFaktaOmFeilutbetaling;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/feilutbetaling';
};

export type BehandlingOppdaterFaktaErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingOppdaterFaktaError =
    BehandlingOppdaterFaktaErrors[keyof BehandlingOppdaterFaktaErrors];

export type BehandlingOppdaterFaktaResponses = {
    /**
     * The request has succeeded.
     */
    200: FaktaOmFeilutbetaling;
};

export type BehandlingOppdaterFaktaResponse =
    BehandlingOppdaterFaktaResponses[keyof BehandlingOppdaterFaktaResponses];

export type BehandlingForeslaaVedtakData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/foreslå-vedtak';
};

export type BehandlingForeslaaVedtakErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingForeslaaVedtakError =
    BehandlingForeslaaVedtakErrors[keyof BehandlingForeslaaVedtakErrors];

export type BehandlingForeslaaVedtakResponses = {
    /**
     * The request has succeeded.
     */
    200: unknown;
};

export type BehandlingHentVedtaksbrevData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/vedtak/brev';
};

export type BehandlingHentVedtaksbrevErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingHentVedtaksbrevError =
    BehandlingHentVedtaksbrevErrors[keyof BehandlingHentVedtaksbrevErrors];

export type BehandlingHentVedtaksbrevResponses = {
    /**
     * The request has succeeded.
     */
    200: VedtaksbrevData;
};

export type BehandlingHentVedtaksbrevResponse =
    BehandlingHentVedtaksbrevResponses[keyof BehandlingHentVedtaksbrevResponses];

export type BehandlingOppdaterVedtaksbrevData = {
    body: VedtaksbrevRedigerbareDataUpdate;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/vedtak/brev';
};

export type BehandlingOppdaterVedtaksbrevErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingOppdaterVedtaksbrevError =
    BehandlingOppdaterVedtaksbrevErrors[keyof BehandlingOppdaterVedtaksbrevErrors];

export type BehandlingOppdaterVedtaksbrevResponses = {
    /**
     * The request has succeeded.
     */
    200: VedtaksbrevRedigerbareData;
};

export type BehandlingOppdaterVedtaksbrevResponse =
    BehandlingOppdaterVedtaksbrevResponses[keyof BehandlingOppdaterVedtaksbrevResponses];

export type BehandlingHentVedtaksresultatData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/vedtak/resultat';
};

export type BehandlingHentVedtaksresultatErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingHentVedtaksresultatError =
    BehandlingHentVedtaksresultatErrors[keyof BehandlingHentVedtaksresultatErrors];

export type BehandlingHentVedtaksresultatResponses = {
    /**
     * The request has succeeded.
     */
    200: Beregningsresultat;
};

export type BehandlingHentVedtaksresultatResponse =
    BehandlingHentVedtaksresultatResponses[keyof BehandlingHentVedtaksresultatResponses];

export type VedtaksbrevLagSvgVedtaksbrevData = {
    body: VedtaksbrevDataWritable;
    path?: never;
    query?: never;
    url: '/api/v1/brev/vedtaksbrev/svg';
};

export type VedtaksbrevLagSvgVedtaksbrevResponses = {
    /**
     * The request has succeeded.
     */
    200: unknown;
};
