// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://raw.githubusercontent.com' | (string & {});
};

export type Avsnitt = {
    tittel: string;
    readonly forklaring: string;
    readonly meldingerTilSaksbehandler: Array<string>;
    id: string;
    underavsnitt: Array<RotElement>;
};

export type AvsnittUpdateItem = {
    tittel: string;
    id: string;
    underavsnitt: Array<RotElementUpdateItem>;
};

export type Beregningsresultat = {
    beregningsresultatsperioder: Array<Beregningsresultatsperiode>;
    vedtaksresultat: Vedtaksresultat;
};

export type BeregningsresultatVurdering = 'GodTro' | 'Forsett' | 'Uaktsomhet' | 'GrovUaktsomhet';

export type Beregningsresultatsperiode = {
    fom: string;
    tom: string;
    feilutbetaltBeløp: number;
    vurdering: BeregningsresultatVurdering;
    andelAvBeløp: number | null;
    renteprosent: number | null;
    tilbakekrevingsbeløp: number;
    tilbakekrevesBeløpEtterSkatt: number;
};

export type BestemmelseEllerGrunnlag = {
    nøkkel: string;
    beskrivelse: string;
};

export type Brevmottaker = {
    navn: string;
    personIdent: string;
};

export type Element = {
    type: 'rentekst';
} & RentekstElement;

export type Error = {
    tittel: string;
    melding: string;
};

export type FaktaOmFeilutbetaling = {
    feilutbetaling: Feilutbetaling;
    tidligereVarsletBeløp: number | null;
    muligeRettsligGrunnlag: Array<MuligeRettsligGrunnlag>;
    perioder: Array<FaktaPeriode>;
    vurdering: Vurdering;
    ferdigvurdert: boolean;
};

export type FaktaPeriode = {
    id: string;
    fom: string;
    tom: string;
    feilutbetaltBeløp: number;
    splittbarePerioder: Array<{
        id: string;
        fom: string;
        tom: string;
        feilutbetaltBeløp: number;
        rettsligGrunnlag: Array<RettsligGrunnlag>;
    }>;
    rettsligGrunnlag: Array<RettsligGrunnlag>;
};

export type Feilutbetaling = {
    beløp: number;
    fom: string;
    tom: string;
    revurdering: Revurdering;
};

export type ForhaandsvarselErSendt = {
    forhåndsvarselInfo: ForhaandsvarselInfo;
    uttalelsesfrist: Uttalelsesfrist;
};

export type ForhaandsvarselInfo = {
    tekstFraSaksbehandler: string;
    varselbrevSendtTid: string;
};

export type ForhaandsvarselResponse = {
    forhaandsvarselSteg: ForhaandsvarselSteg;
    brukeruttalelse: Uttalelse | null;
};

export type ForhaandsvarselSteg =
    | ({
          type: 'ikke_vurdert';
      } & IkkeVurdert)
    | ({
          type: 'sendt';
      } & ForhaandsvarselErSendt)
    | ({
          type: 'unntak';
      } & ForhaandsvarselUnntak);

export type ForhaandsvarselUnntak = {
    begrunnelseForUnntak: Varslingsunntak;
    beskrivelse: string;
};

export type Fritekst = string;

export type Hovedavsnitt = {
    tittel: string;
    readonly forklaring: string;
    underavsnitt: Array<RotElement>;
    hjemler: string;
};

export type HovedavsnittUpdate = {
    tittel: string;
    underavsnitt: Array<RotElementUpdateItem>;
};

export type IkkeVurdert = {
    [key: string]: unknown;
};

export type Logginnslag = {
    behandlingId: string;
    opprettetTid: string;
    type: string;
    aktør: string;
    aktørIdent: string;
    tittel: string;
    tekst: string | null;
    steg: string | null;
    journalpostId: string | null;
    dokumentInfoId: string | null;
};

export type MuligeRettsligGrunnlag = {
    bestemmelse: BestemmelseEllerGrunnlag;
    grunnlag: Array<BestemmelseEllerGrunnlag>;
};

export type Oppdaget = {
    dato: string | null;
    av: AvEnum;
    beskrivelse: Fritekst | null;
};

export type OppdaterFaktaOmFeilutbetaling = {
    perioder?: Array<OppdaterFaktaPeriode>;
    vurdering?: Vurdering;
};

export type OppdaterFaktaPeriode = {
    id: string;
    rettsligGrunnlag: Array<RettsligGrunnlag>;
};

export type Oppsummeringsdata = {
    beregnerSkatt: boolean;
    perioder: Array<OppsummertPeriode>;
    sumFeilutbetaltBeløp: string;
    sumTilbakekrevesBeløpEtterSkatt: string;
};

export type OppsummertPeriode = {
    fom: string;
    tom: string;
    feilutbetaltBeløp: string;
    vurdering: string;
    andelAvBeløp: string;
    renteprosent: string;
    tilbakekrevingsbeløp: string;
    tilbakekrevesBeløpEtterSkatt: string;
};

export type PakrevdBegrunnelse = {
    tittel: string;
    readonly forklaring: string;
    readonly meldingerTilSaksbehandler: Array<string>;
    begrunnelseType: string;
    underavsnitt: Array<Element>;
};

export type PakrevdBegrunnelseUpdateItem = {
    begrunnelseType: string;
    underavsnitt: Array<Element>;
};

export type RentekstElement = {
    tekst: string;
};

export type RettsligGrunnlag = {
    bestemmelse: string;
    grunnlag: string;
};

export type Revurdering = {
    årsak: string;
    vedtaksdato: string;
    resultat: ResultatEnum;
};

export type RotElement =
    | ({
          type: 'rentekst';
      } & RentekstElement)
    | ({
          type: 'underavsnitt';
      } & UnderavsnittElement)
    | ({
          type: 'påkrevd_begrunnelse';
      } & PakrevdBegrunnelse);

export type RotElementUpdateItem =
    | ({
          type: 'rentekst';
      } & RentekstElement)
    | ({
          type: 'underavsnitt';
      } & UnderavsnittElement)
    | ({
          type: 'påkrevd_begrunnelse';
      } & PakrevdBegrunnelseUpdateItem);

export type SendForhaandsvarsel = {
    tekstFraSaksbehandler: string;
};

export type Signatur = {
    enhetNavn: string;
    ansvarligSaksbehandler: string;
    besluttendeSaksbehandler: string | null;
};

export type Standardtekst = {
    tittel: string;
    underavsnitt: Array<Element>;
};

export type UnderavsnittElement = {
    tittel: string;
    underavsnitt: Array<Element>;
};

export type UpdateUttalelsesfrist = {
    nyFrist?: string;
    begrunnelse?: string;
};

export type Uttalelse = {
    harBrukerUttaltSeg: UttalelseVurdering;
    uttalelsesdato?: string;
    hvorBrukerenUttalteSeg?: string;
    beskrivelse?: string;
};

export type UttalelseVurdering =
    | 'JA_ETTER_FORHÅNDSVARSEL'
    | 'NEI_ETTER_FORHÅNDSVARSEL'
    | 'UNNTAK_ALLEREDE_UTTALT_SEG'
    | 'UNNTAK_INGEN_UTTALELSE'
    | 'IKKE_VURDERT';

export type Uttalelsesfrist = {
    nyFrist?: string;
    begrunnelse?: string;
    readonly opprinneligFrist: string;
};

export type Varslingsunntak =
    | 'IKKE_PRAKTISK_MULIG'
    | 'UKJENT_ADRESSE_ELLER_URIMELIG_ETTERSPORING'
    | 'ÅPENBART_UNØDVENDIG'
    | 'ALLEREDE_UTTALET_SEG';

export type VedtaksbrevData = {
    hovedavsnitt: Hovedavsnitt;
    avsnitt: Array<Avsnitt>;
    readonly sistOppdatert: string;
    brevGjelder: Brevmottaker;
    sendtDato: string;
    ytelse: Ytelse;
    signatur: Signatur;
    oppsummeringstabell: Oppsummeringsdata;
    bunntekster: Array<Standardtekst>;
    saksnummer: string;
};

export type VedtaksbrevRedigerbareData = {
    hovedavsnitt: Hovedavsnitt;
    avsnitt: Array<Avsnitt>;
    readonly sistOppdatert: string;
};

export type VedtaksbrevRedigerbareDataUpdate = {
    hovedavsnitt: HovedavsnittUpdate;
    avsnitt: Array<AvsnittUpdateItem>;
};

export type Vedtaksresultat =
    | 'IngenTilbakebetaling'
    | 'DelvisTilbakebetaling'
    | 'FullTilbakebetaling';

export type Vurdering = {
    årsak: Fritekst | null;
    oppdaget?: Oppdaget;
};

export type Ytelse = {
    url: string;
    ubestemtEntall: string;
    bestemtEntall: string;
};

export type AvEnum = 'NAV' | 'BRUKER' | 'IKKE_VURDERT';

export type ResultatEnum = 'INNVILGET' | 'OPPHØRT';

export type AvsnittWritable = {
    tittel: string;
    id: string;
    underavsnitt: Array<RotElementWritable>;
};

export type ForhaandsvarselErSendtWritable = {
    forhåndsvarselInfo: ForhaandsvarselInfo;
    uttalelsesfrist: UttalelsesfristWritable;
};

export type ForhaandsvarselResponseWritable = {
    forhaandsvarselSteg: ForhaandsvarselStegWritable;
    brukeruttalelse: Uttalelse | null;
};

export type ForhaandsvarselStegWritable =
    | ({
          type: 'ikke_vurdert';
      } & IkkeVurdert)
    | ({
          type: 'sendt';
      } & ForhaandsvarselErSendtWritable)
    | ({
          type: 'unntak';
      } & ForhaandsvarselUnntak);

export type HovedavsnittWritable = {
    tittel: string;
    underavsnitt: Array<RotElementWritable>;
    hjemler: string;
};

export type PakrevdBegrunnelseWritable = {
    tittel: string;
    begrunnelseType: string;
    underavsnitt: Array<Element>;
};

export type RotElementWritable =
    | ({
          type: 'rentekst';
      } & RentekstElement)
    | ({
          type: 'underavsnitt';
      } & UnderavsnittElement)
    | ({
          type: 'påkrevd_begrunnelse';
      } & PakrevdBegrunnelseWritable);

export type UttalelsesfristWritable = {
    nyFrist?: string;
    begrunnelse?: string;
};

export type VedtaksbrevDataWritable = {
    hovedavsnitt: HovedavsnittWritable;
    avsnitt: Array<AvsnittWritable>;
    brevGjelder: Brevmottaker;
    sendtDato: string;
    ytelse: Ytelse;
    signatur: Signatur;
    oppsummeringstabell: Oppsummeringsdata;
    bunntekster: Array<Standardtekst>;
    saksnummer: string;
};

export type VedtaksbrevRedigerbareDataWritable = {
    hovedavsnitt: HovedavsnittWritable;
    avsnitt: Array<AvsnittWritable>;
};

export type BehandlingBehandlingsloggData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/behandlingslogg';
};

export type BehandlingBehandlingsloggErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingBehandlingsloggError =
    BehandlingBehandlingsloggErrors[keyof BehandlingBehandlingsloggErrors];

export type BehandlingBehandlingsloggResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<Logginnslag>;
};

export type BehandlingBehandlingsloggResponse =
    BehandlingBehandlingsloggResponses[keyof BehandlingBehandlingsloggResponses];

export type BehandlingFaktaData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/feilutbetaling';
};

export type BehandlingFaktaErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingFaktaError = BehandlingFaktaErrors[keyof BehandlingFaktaErrors];

export type BehandlingFaktaResponses = {
    /**
     * The request has succeeded.
     */
    200: FaktaOmFeilutbetaling;
};

export type BehandlingFaktaResponse = BehandlingFaktaResponses[keyof BehandlingFaktaResponses];

export type BehandlingOppdaterFaktaData = {
    body: OppdaterFaktaOmFeilutbetaling;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/feilutbetaling';
};

export type BehandlingOppdaterFaktaErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingOppdaterFaktaError =
    BehandlingOppdaterFaktaErrors[keyof BehandlingOppdaterFaktaErrors];

export type BehandlingOppdaterFaktaResponses = {
    /**
     * The request has succeeded.
     */
    200: FaktaOmFeilutbetaling;
};

export type BehandlingOppdaterFaktaResponse =
    BehandlingOppdaterFaktaResponses[keyof BehandlingOppdaterFaktaResponses];

export type BehandlingForeslaaVedtakData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/foreslå-vedtak';
};

export type BehandlingForeslaaVedtakErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingForeslaaVedtakError =
    BehandlingForeslaaVedtakErrors[keyof BehandlingForeslaaVedtakErrors];

export type BehandlingForeslaaVedtakResponses = {
    /**
     * The request has succeeded.
     */
    200: unknown;
};

export type BehandlingForhandsvarselData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel';
};

export type BehandlingForhandsvarselErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingForhandsvarselError =
    BehandlingForhandsvarselErrors[keyof BehandlingForhandsvarselErrors];

export type BehandlingForhandsvarselResponses = {
    /**
     * The request has succeeded.
     */
    200: ForhaandsvarselResponse;
};

export type BehandlingForhandsvarselResponse =
    BehandlingForhandsvarselResponses[keyof BehandlingForhandsvarselResponses];

export type BehandlingSendVarselbrevData = {
    body: SendForhaandsvarsel;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel/send-varselbrev';
};

export type BehandlingSendVarselbrevErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingSendVarselbrevError =
    BehandlingSendVarselbrevErrors[keyof BehandlingSendVarselbrevErrors];

export type BehandlingSendVarselbrevResponses = {
    /**
     * The request has succeeded.
     */
    200: unknown;
};

export type BehandlingLagreForhaandsvarselUnntakData = {
    body: ForhaandsvarselUnntak;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel/unntak';
};

export type BehandlingLagreForhaandsvarselUnntakErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingLagreForhaandsvarselUnntakError =
    BehandlingLagreForhaandsvarselUnntakErrors[keyof BehandlingLagreForhaandsvarselUnntakErrors];

export type BehandlingLagreForhaandsvarselUnntakResponses = {
    /**
     * The request has succeeded.
     */
    200: unknown;
};

export type BehandlingUtsettUttalelsesfristData = {
    body: UpdateUttalelsesfrist;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel/utsett-frist';
};

export type BehandlingUtsettUttalelsesfristErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingUtsettUttalelsesfristError =
    BehandlingUtsettUttalelsesfristErrors[keyof BehandlingUtsettUttalelsesfristErrors];

export type BehandlingUtsettUttalelsesfristResponses = {
    /**
     * The request has succeeded.
     */
    200: Uttalelsesfrist;
};

export type BehandlingUtsettUttalelsesfristResponse =
    BehandlingUtsettUttalelsesfristResponses[keyof BehandlingUtsettUttalelsesfristResponses];

export type BehandlingLagreBrukersuttalelseData = {
    body: Uttalelse;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel/uttalelse';
};

export type BehandlingLagreBrukersuttalelseErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingLagreBrukersuttalelseError =
    BehandlingLagreBrukersuttalelseErrors[keyof BehandlingLagreBrukersuttalelseErrors];

export type BehandlingLagreBrukersuttalelseResponses = {
    /**
     * The request has succeeded.
     */
    200: unknown;
};

export type BehandlingHentVedtaksbrevData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/vedtak/brev';
};

export type BehandlingHentVedtaksbrevErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingHentVedtaksbrevError =
    BehandlingHentVedtaksbrevErrors[keyof BehandlingHentVedtaksbrevErrors];

export type BehandlingHentVedtaksbrevResponses = {
    /**
     * The request has succeeded.
     */
    200: VedtaksbrevData;
};

export type BehandlingHentVedtaksbrevResponse =
    BehandlingHentVedtaksbrevResponses[keyof BehandlingHentVedtaksbrevResponses];

export type BehandlingOppdaterVedtaksbrevData = {
    body: VedtaksbrevRedigerbareDataUpdate;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/vedtak/brev';
};

export type BehandlingOppdaterVedtaksbrevErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingOppdaterVedtaksbrevError =
    BehandlingOppdaterVedtaksbrevErrors[keyof BehandlingOppdaterVedtaksbrevErrors];

export type BehandlingOppdaterVedtaksbrevResponses = {
    /**
     * The request has succeeded.
     */
    200: VedtaksbrevRedigerbareData;
};

export type BehandlingOppdaterVedtaksbrevResponse =
    BehandlingOppdaterVedtaksbrevResponses[keyof BehandlingOppdaterVedtaksbrevResponses];

export type BehandlingHentVedtaksresultatData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/vedtak/resultat';
};

export type BehandlingHentVedtaksresultatErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingHentVedtaksresultatError =
    BehandlingHentVedtaksresultatErrors[keyof BehandlingHentVedtaksresultatErrors];

export type BehandlingHentVedtaksresultatResponses = {
    /**
     * The request has succeeded.
     */
    200: Beregningsresultat;
};

export type BehandlingHentVedtaksresultatResponse =
    BehandlingHentVedtaksresultatResponses[keyof BehandlingHentVedtaksresultatResponses];

export type VedtaksbrevLagSvgVedtaksbrevData = {
    body: VedtaksbrevDataWritable;
    path?: never;
    query?: never;
    url: '/api/v1/brev/vedtaksbrev/svg';
};

export type VedtaksbrevLagSvgVedtaksbrevResponses = {
    /**
     * The request has succeeded.
     */
    200: Blob | File;
};

export type VedtaksbrevLagSvgVedtaksbrevResponse =
    VedtaksbrevLagSvgVedtaksbrevResponses[keyof VedtaksbrevLagSvgVedtaksbrevResponses];
