// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://raw.githubusercontent.com' | (string & {});
};

export type Aktsomhet =
    | ({
          aktsomhet: 'uaktsomt';
      } & Uaktsomt)
    | ({
          aktsomhet: 'grovtUaktsomt';
      } & GrovtUaktsomt)
    | ({
          aktsomhet: 'forsettlig';
      } & Forsettlig);

export type ArsakTilTilbakeforing = 'NyttKravgrunnlag' | 'TilbakemeldingFraSaksbehandler';

export type Avsnitt = {
    tittel: string;
    readonly forklaring: string;
    readonly meldingerTilSaksbehandler: Array<string>;
    id: string;
    underavsnitt: Array<RotElement>;
};

export type AvsnittUpdateItem = {
    tittel: string;
    id: string;
    underavsnitt: Array<RotElementUpdateItem>;
};

export type Behandling = {
    kravgrunnlagEndret?: Array<KravgrunnlagForskjell>;
};

export type BelopIBehold =
    | ({
          belopIBehold: 'ingenting';
      } & Ingenting)
    | ({
          belopIBehold: 'hele';
      } & Hele)
    | ({
          belopIBehold: 'deler';
      } & Deler);

export type Beregningsresultat = {
    beregningsresultatsperioder: Array<Beregningsresultatsperiode>;
    vedtaksresultat: Vedtaksresultat;
};

export type BeregningsresultatVurdering =
    | 'GodTro'
    | 'Forsett'
    | 'Uaktsomhet'
    | 'GrovUaktsomhet'
    | 'BurdeForstått'
    | 'Forstod';

export type Beregningsresultatsperiode = {
    readonly fom: string;
    readonly tom: string;
    feilutbetaltBeløp: number;
    vurdering: BeregningsresultatVurdering;
    andelAvBeløp: number | null;
    renteprosent: number | null;
    tilbakekrevingsbeløp: number;
    tilbakekrevesBeløpEtterSkatt: number;
};

export type BestemmelseEllerGrunnlag = {
    nøkkel: string;
    beskrivelse: string;
};

export type Brevmottaker = {
    navn: string;
    personIdent: string;
};

export type BurdeForstaatt = {
    begrunnelse: string;
    unnlatelse: Unnlatelse;
};

export type Deler = {
    beløp: number;
    begrunnelse: string;
    reduksjon: ReduksjonArsaker;
};

export type DokumentInfo = {
    journalpostId: string | null;
    dokumentId: string | null;
};

export type DokumentType = 'VARSELBREV' | 'VEDTAKSBREV';

export type Element = RentekstElement;

export type EndretPeriode = {
    readonly fom: string;
    readonly tom: string;
    endringIBeløp: number;
};

export type Error = {
    tittel: string;
    melding: string;
};

export type Fakta = {
    rettsligGrunnlag: Array<string>;
};

export type FaktaOmFeilutbetaling = {
    readonly tilbakeført?: ArsakTilTilbakeforing;
    readonly ferdigvurdert: boolean;
    feilutbetaling: Feilutbetaling;
    tidligereVarsletBeløp: number | null;
    muligeRettsligGrunnlag: Array<MuligeRettsligGrunnlag>;
    perioder: Array<FaktaPeriode>;
    vurdering: Vurdering;
    rettsgebyrÅrFraSaksbehandler: number | null;
    readonly usikker4xRettsgebyr: boolean;
};

export type FaktaPeriode = {
    id: string;
    readonly fom: string;
    readonly tom: string;
    readonly endringIKravgrunnlag?: KravgrunnlagForskjell;
    feilutbetaltBeløp: number;
    splittbarePerioder: Array<{
        id: string;
        readonly fom: string;
        readonly tom: string;
        readonly endringIKravgrunnlag?: KravgrunnlagForskjell;
        feilutbetaltBeløp: number;
        rettsligGrunnlag: Array<RettsligGrunnlag>;
    }>;
    rettsligGrunnlag: Array<RettsligGrunnlag>;
};

export type Feilutbetaling = {
    beløp: number;
    readonly fom: string;
    readonly tom: string;
    revurdering: Revurdering;
};

export type ForaarsaketAvMottaker = {
    aktsomhet: Aktsomhet;
};

export type ForhaandsvarselErSendt = {
    readonly tilbakeført?: ArsakTilTilbakeforing;
    readonly ferdigvurdert: boolean;
    forhåndsvarselInfo: ForhaandsvarselInfo;
    uttalelsesfrist: Uttalelsesfrist;
};

export type ForhaandsvarselInfo = {
    tekstFraSaksbehandler: string;
    varselbrevSendtTid: string;
};

export type ForhaandsvarselResponse = {
    forhaandsvarselSteg: ForhaandsvarselSteg;
    brukeruttalelse: Uttalelse | null;
};

export type ForhaandsvarselSteg =
    | ({
          type: 'ikke_vurdert';
      } & IkkeVurdert)
    | ({
          type: 'sendt';
      } & ForhaandsvarselErSendt)
    | ({
          type: 'unntak';
      } & ForhaandsvarselUnntak);

export type ForhaandsvarselUnntak = {
    readonly tilbakeført?: ArsakTilTilbakeforing;
    readonly ferdigvurdert: boolean;
    begrunnelseForUnntak: Varslingsunntak;
    beskrivelse: string;
};

export type Forsettlig = {
    begrunnelse: string;
};

export type Forstaaelse =
    | ({
          forståelse: 'forsto';
      } & Forsto)
    | ({
          forståelse: 'burdeForstått';
      } & BurdeForstaatt);

export type Forsto = {
    begrunnelse: string;
    unnlatelse: Unnlatelse;
};

export type ForstoEllerBurdeForstaatt = {
    forståelse: Forstaaelse;
};

export type Fritekst = string;

export type GodTro = {
    begrunnelse: string;
    beløpIBehold: BelopIBehold;
};

export type GrovtUaktsomt = {
    begrunnelse: string;
    erDetSærligeGrunner: ReduksjonArsaker;
};

export type Hele = {
    begrunnelse: string;
    reduksjon: ReduksjonArsaker;
};

export type Hovedavsnitt = {
    tittel: string;
    readonly forklaring: string;
    underavsnitt: Array<RotElement>;
    hjemler: string;
};

export type HovedavsnittUpdate = {
    tittel: string;
    underavsnitt: Array<RotElementUpdateItem>;
};

export type HovedavsnittVarselbrev = {
    tittel: string;
    innhold: Array<string>;
};

export type IkkeAktuelt = {
    erDetSærligeGrunner: ReduksjonArsaker;
};

export type IkkeVurdert = {
    [key: string]: unknown;
};

export type Ingenting = {
    begrunnelse: string;
};

export type JaSaerligeGrunner = {
    særligeGrunnerFor: Array<Moment>;
    prosentReduksjon: number;
    begrunnelse: string;
    annetBegrunnelse: string | null;
};

export type KravgrunnlagForskjell =
    | ({
          type: 'ny_periode';
      } & NyPeriode)
    | ({
          type: 'endret_periode';
      } & EndretPeriode);

export type Logginnslag = {
    behandlingId: string;
    opprettetTid: string;
    type: string;
    aktør: string;
    aktørIdent: string;
    tittel: string;
    tekst: string | null;
    steg: string | null;
    ekstraInfo: {
        [key: string]: unknown;
    };
};

export type Moment = {
    moment: string;
    readonly beskrivelse: string;
};

export type MuligeRettsligGrunnlag = {
    bestemmelse: BestemmelseEllerGrunnlag;
    grunnlag: Array<BestemmelseEllerGrunnlag>;
};

export type NeiSaerligeGrunner = {
    særligeGrunnerMot: Array<Moment>;
    begrunnelse: string;
    annetBegrunnelse: string | null;
};

export type NyPeriode = {
    readonly fom: string;
    readonly tom: string;
    beløp: number;
};

export type Oppdaget = {
    dato: string | null;
    av: AvEnum;
    beskrivelse: Fritekst | null;
};

export type OppdaterFaktaOmFeilutbetaling = {
    perioder?: Array<OppdaterFaktaPeriode>;
    vurdering?: Vurdering;
    rettsgebyrÅrFraSaksbehandler: number | null;
};

export type OppdaterFaktaPeriode = {
    id: string;
    rettsligGrunnlag: Array<RettsligGrunnlag>;
};

export type Oppsummeringsdata = {
    beregnerSkatt: boolean;
    perioder: Array<OppsummertPeriode>;
    sumFeilutbetaltBeløp: string;
    sumTilbakekrevesBeløpEtterSkatt: string;
};

export type OppsummertPeriode = {
    fom: string;
    tom: string;
    feilutbetaltBeløp: string;
    vurdering: string;
    andelAvBeløp: string;
    renteprosent: string;
    tilbakekrevingsbeløp: string;
    tilbakekrevesBeløpEtterSkatt: string;
};

export type PakrevdBegrunnelse = {
    tittel: string;
    readonly forklaring: string;
    readonly meldingerTilSaksbehandler: Array<string>;
    begrunnelseType: string;
    underavsnitt: Array<Element>;
};

export type PakrevdBegrunnelseUpdateItem = {
    begrunnelseType: string;
    underavsnitt: Array<Element>;
};

export type Periode = {
    readonly fom: string;
    readonly tom: string;
};

export type PeriodeInfo = {
    periodeId: string;
    periode: Periode;
};

export type ReduksjonArsaker =
    | ({
          erDetReduksjonÅrsaker: 'nei';
      } & NeiSaerligeGrunner)
    | ({
          erDetReduksjonÅrsaker: 'ja';
      } & JaSaerligeGrunner)
    | ({
          erDetReduksjonÅrsaker: 'neiGodTro';
      } & SkalIkkeReduseres)
    | ({
          erDetReduksjonÅrsaker: 'jaGodTro';
      } & SkalReduseres);

export type RentekstElement = {
    tekst: string;
};

export type RettsligGrunnlag = {
    bestemmelse: string;
    grunnlag: string;
};

export type Revurdering = {
    årsak: string;
    vedtaksdato: string;
    resultat: ResultatEnum;
};

export type RotElement =
    | ({
          type: 'rentekst';
      } & RentekstElement)
    | ({
          type: 'underavsnitt';
      } & UnderavsnittElement)
    | ({
          type: 'påkrevd_begrunnelse';
      } & PakrevdBegrunnelse);

export type RotElementUpdateItem =
    | ({
          type: 'rentekst';
      } & RentekstElement)
    | ({
          type: 'underavsnitt';
      } & UnderavsnittElement)
    | ({
          type: 'påkrevd_begrunnelse';
      } & PakrevdBegrunnelseUpdateItem);

export type Sammenslaaing = {
    vilkårsvurderingId: string;
    slåesSammenMedId: string;
};

export type Section = {
    tittel: string;
    body: Array<string>;
};

export type SendForhaandsvarsel = {
    tekstFraSaksbehandler: string;
};

export type Signatur = {
    enhetNavn: string;
    ansvarligSaksbehandler: string;
    besluttendeSaksbehandler: string | null;
};

export type SkalIkkeReduseres = {
    relevans: Array<Moment>;
    annetBegrunnelse: string | null;
    begrunnelse: string;
};

export type SkalIkkeUnnlates = {
    begrunnelse: string;
    erDetSærligeGrunner: ReduksjonArsaker;
};

export type SkalReduseres = {
    prosentReduksjon: number;
    relevans: Array<Moment>;
    annetBegrunnelse: string | null;
    begrunnelse: string;
};

export type SkalUnnlates = {
    begrunnelse: string;
};

export type SplittPeriode = {
    vilkårsvurderingId: string;
};

export type Standardtekst = {
    tittel: string;
    underavsnitt: Array<Element>;
};

export type Uaktsomt = {
    begrunnelse: string;
    unnlatelse: Unnlatelse;
};

export type UnderavsnittElement = {
    tittel: string;
    underavsnitt: Array<Element>;
};

export type Unnlatelse =
    | ({
          unnlatelse: 'skalUnnlates';
      } & SkalUnnlates)
    | ({
          unnlatelse: 'skalIkkeUnnlates';
      } & SkalIkkeUnnlates)
    | ({
          unnlatelse: 'ikkeAktuelt';
      } & IkkeAktuelt);

export type Unntak = {
    begrunnelseForUnntak: Varslingsunntak;
    beskrivelse: string;
};

export type UpdateUttalelsesfrist = {
    nyFrist?: string;
    begrunnelse?: string;
};

export type Uttalelse = {
    harBrukerUttaltSeg: UttalelseVurdering;
    uttalelsesdato?: string;
    hvorBrukerenUttalteSeg?: string;
    beskrivelse?: string;
};

export type UttalelseVurdering =
    | 'JA_ETTER_FORHÅNDSVARSEL'
    | 'NEI_ETTER_FORHÅNDSVARSEL'
    | 'UNNTAK_ALLEREDE_UTTALT_SEG'
    | 'UNNTAK_INGEN_UTTALELSE'
    | 'IKKE_VURDERT';

export type Uttalelsesfrist = {
    nyFrist?: string;
    begrunnelse?: string;
    readonly opprinneligFrist: string;
};

export type VarselbrevData = {
    hovedavsnitt: HovedavsnittVarselbrev;
    underavsnitt: Array<UnderavsnittElement>;
    brevGjelder: Brevmottaker;
    signatur: Signatur;
    sendtDato: string;
    saksnummer: string;
};

export type VarselbrevTekst = {
    overskrift: string;
    avsnitter: Array<Section>;
};

export type Varslingsunntak =
    | 'IKKE_PRAKTISK_MULIG'
    | 'UKJENT_ADRESSE_ELLER_URIMELIG_ETTERSPORING'
    | 'ÅPENBART_UNØDVENDIG'
    | 'ALLEREDE_UTTALET_SEG';

export type VedtaksbrevData = {
    hovedavsnitt: Hovedavsnitt;
    avsnitt: Array<Avsnitt>;
    readonly sistOppdatert: string;
    brevGjelder: Brevmottaker;
    sendtDato: string;
    ytelse: Ytelse;
    signatur: Signatur;
    oppsummeringstabell: Oppsummeringsdata;
    bunntekster: Array<Standardtekst>;
    saksnummer: string;
};

export type VedtaksbrevRedigerbareData = {
    hovedavsnitt: Hovedavsnitt;
    avsnitt: Array<Avsnitt>;
    readonly sistOppdatert: string;
};

export type VedtaksbrevRedigerbareDataUpdate = {
    hovedavsnitt: HovedavsnittUpdate;
    avsnitt: Array<AvsnittUpdateItem>;
};

export type Vedtaksresultat =
    | 'IngenTilbakebetaling'
    | 'DelvisTilbakebetaling'
    | 'FullTilbakebetaling';

export type Vilkaar = {
    readonly tilbakeført?: ArsakTilTilbakeforing;
    readonly ferdigvurdert: boolean;
    vilkårsperioder: Array<Vilkaarsperiode>;
    readonly momenterSærligeGrunner: Array<Moment>;
    readonly momenterReduksjonGodTro: Array<Moment>;
    readonly erUnder4xRettsgebyr: boolean;
};

export type Vilkaarsperiode = {
    readonly feilutbetaltBeløp: number;
    delresultat: DelresultatEnum;
    readonly fakta: Fakta;
    readonly simulertBeløp: number;
    vilkårsvurdering: Vilkaarsvurdering;
};

export type Vilkaarsvurdering = {
    id: string;
    readonly fom: string;
    readonly tom: string;
    readonly endringIKravgrunnlag?: KravgrunnlagForskjell;
    readonly delbarePerioder: Array<PeriodeInfo>;
    valg: VilkaarsvurderingValg;
};

export type VilkaarsvurderingIkkeVurdert = {
    [key: string]: unknown;
};

export type VilkaarsvurderingValg =
    | ({
          vurdering: 'god_tro';
      } & GodTro)
    | ({
          vurdering: 'forårsaket_av_mottaker';
      } & ForaarsaketAvMottaker)
    | ({
          vurdering: 'forsto_eller_burde_forstått';
      } & ForstoEllerBurdeForstaatt)
    | ({
          vurdering: 'ikke_vurdert';
      } & VilkaarsvurderingIkkeVurdert);

export type Vurdering = {
    årsak: Fritekst | null;
    oppdaget?: Oppdaget;
};

export type Ytelse = {
    url: string;
    ubestemtEntall: string;
    bestemtEntall: string;
};

export type AvEnum = 'NAV' | 'BRUKER' | 'IKKE_VURDERT';

export type ResultatEnum = 'INNVILGET' | 'OPPHØRT';

export type DelresultatEnum =
    | 'FULL_TILBAKEKREVING'
    | 'INGEN_TILBAKEKREVING'
    | 'DELVIS_TILBAKEKREVING';

export type AktsomhetWritable =
    | ({
          aktsomhet: 'uaktsomt';
      } & UaktsomtWritable)
    | ({
          aktsomhet: 'grovtUaktsomt';
      } & GrovtUaktsomtWritable)
    | ({
          aktsomhet: 'forsettlig';
      } & Forsettlig);

export type AvsnittWritable = {
    tittel: string;
    id: string;
    underavsnitt: Array<RotElementWritable>;
};

export type BehandlingWritable = {
    kravgrunnlagEndret?: Array<KravgrunnlagForskjellWritable>;
};

export type BelopIBeholdWritable =
    | ({
          belopIBehold: 'ingenting';
      } & Ingenting)
    | ({
          belopIBehold: 'hele';
      } & HeleWritable)
    | ({
          belopIBehold: 'deler';
      } & DelerWritable);

export type BeregningsresultatWritable = {
    beregningsresultatsperioder: Array<BeregningsresultatsperiodeWritable>;
    vedtaksresultat: Vedtaksresultat;
};

export type BeregningsresultatsperiodeWritable = {
    feilutbetaltBeløp: number;
    vurdering: BeregningsresultatVurdering;
    andelAvBeløp: number | null;
    renteprosent: number | null;
    tilbakekrevingsbeløp: number;
    tilbakekrevesBeløpEtterSkatt: number;
};

export type BurdeForstaattWritable = {
    begrunnelse: string;
    unnlatelse: UnnlatelseWritable;
};

export type DelerWritable = {
    beløp: number;
    begrunnelse: string;
    reduksjon: ReduksjonArsakerWritable;
};

export type EndretPeriodeWritable = {
    endringIBeløp: number;
};

export type FaktaOmFeilutbetalingWritable = {
    feilutbetaling: FeilutbetalingWritable;
    tidligereVarsletBeløp: number | null;
    muligeRettsligGrunnlag: Array<MuligeRettsligGrunnlag>;
    perioder: Array<FaktaPeriodeWritable>;
    vurdering: Vurdering;
    rettsgebyrÅrFraSaksbehandler: number | null;
};

export type FaktaPeriodeWritable = {
    id: string;
    feilutbetaltBeløp: number;
    splittbarePerioder: Array<{
        id: string;
        feilutbetaltBeløp: number;
        rettsligGrunnlag: Array<RettsligGrunnlag>;
    }>;
    rettsligGrunnlag: Array<RettsligGrunnlag>;
};

export type FeilutbetalingWritable = {
    beløp: number;
    revurdering: Revurdering;
};

export type ForaarsaketAvMottakerWritable = {
    aktsomhet: AktsomhetWritable;
};

export type ForhaandsvarselErSendtWritable = {
    forhåndsvarselInfo: ForhaandsvarselInfo;
    uttalelsesfrist: UttalelsesfristWritable;
};

export type ForhaandsvarselResponseWritable = {
    forhaandsvarselSteg: ForhaandsvarselStegWritable;
    brukeruttalelse: Uttalelse | null;
};

export type ForhaandsvarselStegWritable =
    | ({
          type: 'ikke_vurdert';
      } & IkkeVurdert)
    | ({
          type: 'sendt';
      } & ForhaandsvarselErSendtWritable)
    | ({
          type: 'unntak';
      } & ForhaandsvarselUnntakWritable);

export type ForhaandsvarselUnntakWritable = {
    begrunnelseForUnntak: Varslingsunntak;
    beskrivelse: string;
};

export type ForstaaelseWritable =
    | ({
          forståelse: 'forsto';
      } & ForstoWritable)
    | ({
          forståelse: 'burdeForstått';
      } & BurdeForstaattWritable);

export type ForstoWritable = {
    begrunnelse: string;
    unnlatelse: UnnlatelseWritable;
};

export type ForstoEllerBurdeForstaattWritable = {
    forståelse: ForstaaelseWritable;
};

export type GodTroWritable = {
    begrunnelse: string;
    beløpIBehold: BelopIBeholdWritable;
};

export type GrovtUaktsomtWritable = {
    begrunnelse: string;
    erDetSærligeGrunner: ReduksjonArsakerWritable;
};

export type HeleWritable = {
    begrunnelse: string;
    reduksjon: ReduksjonArsakerWritable;
};

export type HovedavsnittWritable = {
    tittel: string;
    underavsnitt: Array<RotElementWritable>;
    hjemler: string;
};

export type IkkeAktueltWritable = {
    erDetSærligeGrunner: ReduksjonArsakerWritable;
};

export type JaSaerligeGrunnerWritable = {
    særligeGrunnerFor: Array<MomentWritable>;
    prosentReduksjon: number;
    begrunnelse: string;
    annetBegrunnelse: string | null;
};

export type KravgrunnlagForskjellWritable =
    | ({
          type: 'ny_periode';
      } & NyPeriodeWritable)
    | ({
          type: 'endret_periode';
      } & EndretPeriodeWritable);

export type MomentWritable = {
    moment: string;
};

export type NeiSaerligeGrunnerWritable = {
    særligeGrunnerMot: Array<MomentWritable>;
    begrunnelse: string;
    annetBegrunnelse: string | null;
};

export type NyPeriodeWritable = {
    beløp: number;
};

export type PakrevdBegrunnelseWritable = {
    tittel: string;
    begrunnelseType: string;
    underavsnitt: Array<Element>;
};

export type PeriodeInfoWritable = {
    periodeId: string;
};

export type ReduksjonArsakerWritable =
    | ({
          erDetReduksjonÅrsaker: 'nei';
      } & NeiSaerligeGrunnerWritable)
    | ({
          erDetReduksjonÅrsaker: 'ja';
      } & JaSaerligeGrunnerWritable)
    | ({
          erDetReduksjonÅrsaker: 'neiGodTro';
      } & SkalIkkeReduseresWritable)
    | ({
          erDetReduksjonÅrsaker: 'jaGodTro';
      } & SkalReduseresWritable);

export type RotElementWritable =
    | ({
          type: 'rentekst';
      } & RentekstElement)
    | ({
          type: 'underavsnitt';
      } & UnderavsnittElement)
    | ({
          type: 'påkrevd_begrunnelse';
      } & PakrevdBegrunnelseWritable);

export type SkalIkkeReduseresWritable = {
    relevans: Array<MomentWritable>;
    annetBegrunnelse: string | null;
    begrunnelse: string;
};

export type SkalIkkeUnnlatesWritable = {
    begrunnelse: string;
    erDetSærligeGrunner: ReduksjonArsakerWritable;
};

export type SkalReduseresWritable = {
    prosentReduksjon: number;
    relevans: Array<MomentWritable>;
    annetBegrunnelse: string | null;
    begrunnelse: string;
};

export type UaktsomtWritable = {
    begrunnelse: string;
    unnlatelse: UnnlatelseWritable;
};

export type UnnlatelseWritable =
    | ({
          unnlatelse: 'skalUnnlates';
      } & SkalUnnlates)
    | ({
          unnlatelse: 'skalIkkeUnnlates';
      } & SkalIkkeUnnlatesWritable)
    | ({
          unnlatelse: 'ikkeAktuelt';
      } & IkkeAktueltWritable);

export type UttalelsesfristWritable = {
    nyFrist?: string;
    begrunnelse?: string;
};

export type VedtaksbrevDataWritable = {
    hovedavsnitt: HovedavsnittWritable;
    avsnitt: Array<AvsnittWritable>;
    brevGjelder: Brevmottaker;
    sendtDato: string;
    ytelse: Ytelse;
    signatur: Signatur;
    oppsummeringstabell: Oppsummeringsdata;
    bunntekster: Array<Standardtekst>;
    saksnummer: string;
};

export type VedtaksbrevRedigerbareDataWritable = {
    hovedavsnitt: HovedavsnittWritable;
    avsnitt: Array<AvsnittWritable>;
};

export type VilkaarWritable = {
    vilkårsperioder: Array<VilkaarsperiodeWritable>;
};

export type VilkaarsperiodeWritable = {
    vilkårsvurdering: VilkaarsvurderingWritable;
};

export type VilkaarsvurderingWritable = {
    id: string;
    valg: VilkaarsvurderingValgWritable;
};

export type VilkaarsvurderingValgWritable =
    | ({
          vurdering: 'god_tro';
      } & GodTroWritable)
    | ({
          vurdering: 'forårsaket_av_mottaker';
      } & ForaarsaketAvMottakerWritable)
    | ({
          vurdering: 'forsto_eller_burde_forstått';
      } & ForstoEllerBurdeForstaattWritable)
    | ({
          vurdering: 'ikke_vurdert';
      } & VilkaarsvurderingIkkeVurdert);

export type BehandlingHentBehandlingData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/';
};

export type BehandlingHentBehandlingErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingHentBehandlingError =
    BehandlingHentBehandlingErrors[keyof BehandlingHentBehandlingErrors];

export type BehandlingHentBehandlingResponses = {
    /**
     * The request has succeeded.
     */
    200: Behandling;
};

export type BehandlingHentBehandlingResponse =
    BehandlingHentBehandlingResponses[keyof BehandlingHentBehandlingResponses];

export type BehandlingBehandlingsloggData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/behandlingslogg';
};

export type BehandlingBehandlingsloggErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingBehandlingsloggError =
    BehandlingBehandlingsloggErrors[keyof BehandlingBehandlingsloggErrors];

export type BehandlingBehandlingsloggResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<Logginnslag>;
};

export type BehandlingBehandlingsloggResponse =
    BehandlingBehandlingsloggResponses[keyof BehandlingBehandlingsloggResponses];

export type BehandlingFaktaData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/feilutbetaling';
};

export type BehandlingFaktaErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingFaktaError = BehandlingFaktaErrors[keyof BehandlingFaktaErrors];

export type BehandlingFaktaResponses = {
    /**
     * The request has succeeded.
     */
    200: FaktaOmFeilutbetaling;
};

export type BehandlingFaktaResponse = BehandlingFaktaResponses[keyof BehandlingFaktaResponses];

export type BehandlingOppdaterFaktaData = {
    body: OppdaterFaktaOmFeilutbetaling;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/feilutbetaling';
};

export type BehandlingOppdaterFaktaErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingOppdaterFaktaError =
    BehandlingOppdaterFaktaErrors[keyof BehandlingOppdaterFaktaErrors];

export type BehandlingOppdaterFaktaResponses = {
    /**
     * The request has succeeded.
     */
    200: FaktaOmFeilutbetaling;
};

export type BehandlingOppdaterFaktaResponse =
    BehandlingOppdaterFaktaResponses[keyof BehandlingOppdaterFaktaResponses];

export type BehandlingForeslaaVedtakData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/foreslå-vedtak';
};

export type BehandlingForeslaaVedtakErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingForeslaaVedtakError =
    BehandlingForeslaaVedtakErrors[keyof BehandlingForeslaaVedtakErrors];

export type BehandlingForeslaaVedtakResponses = {
    /**
     * The request has succeeded.
     */
    200: unknown;
};

export type BehandlingForhandsvarselData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel';
};

export type BehandlingForhandsvarselErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingForhandsvarselError =
    BehandlingForhandsvarselErrors[keyof BehandlingForhandsvarselErrors];

export type BehandlingForhandsvarselResponses = {
    /**
     * The request has succeeded.
     */
    200: ForhaandsvarselResponse;
};

export type BehandlingForhandsvarselResponse =
    BehandlingForhandsvarselResponses[keyof BehandlingForhandsvarselResponses];

export type BehandlingSendVarselbrevData = {
    body: SendForhaandsvarsel;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel/send-varselbrev';
};

export type BehandlingSendVarselbrevErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingSendVarselbrevError =
    BehandlingSendVarselbrevErrors[keyof BehandlingSendVarselbrevErrors];

export type BehandlingSendVarselbrevResponses = {
    /**
     * The request has succeeded.
     */
    200: unknown;
};

export type BehandlingLagreForhaandsvarselUnntakData = {
    body: Unntak;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel/unntak';
};

export type BehandlingLagreForhaandsvarselUnntakErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingLagreForhaandsvarselUnntakError =
    BehandlingLagreForhaandsvarselUnntakErrors[keyof BehandlingLagreForhaandsvarselUnntakErrors];

export type BehandlingLagreForhaandsvarselUnntakResponses = {
    /**
     * The request has succeeded.
     */
    200: unknown;
};

export type BehandlingUtsettUttalelsesfristData = {
    body: UpdateUttalelsesfrist;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel/utsett-frist';
};

export type BehandlingUtsettUttalelsesfristErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingUtsettUttalelsesfristError =
    BehandlingUtsettUttalelsesfristErrors[keyof BehandlingUtsettUttalelsesfristErrors];

export type BehandlingUtsettUttalelsesfristResponses = {
    /**
     * The request has succeeded.
     */
    200: Uttalelsesfrist;
};

export type BehandlingUtsettUttalelsesfristResponse =
    BehandlingUtsettUttalelsesfristResponses[keyof BehandlingUtsettUttalelsesfristResponses];

export type BehandlingLagreBrukersuttalelseData = {
    body: Uttalelse;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/forhåndsvarsel/uttalelse';
};

export type BehandlingLagreBrukersuttalelseErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingLagreBrukersuttalelseError =
    BehandlingLagreBrukersuttalelseErrors[keyof BehandlingLagreBrukersuttalelseErrors];

export type BehandlingLagreBrukersuttalelseResponses = {
    /**
     * The request has succeeded.
     */
    200: unknown;
};

export type BehandlingHentDokumentData = {
    body?: never;
    path: {
        behandlingId: string;
        journalpostId: string;
        dokumentInfoId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/journalpost/{journalpostId}/dokument/{dokumentInfoId}';
};

export type BehandlingHentDokumentErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingHentDokumentError =
    BehandlingHentDokumentErrors[keyof BehandlingHentDokumentErrors];

export type BehandlingHentDokumentResponses = {
    /**
     * The request has succeeded.
     */
    200: Blob | File;
};

export type BehandlingHentDokumentResponse =
    BehandlingHentDokumentResponses[keyof BehandlingHentDokumentResponses];

export type BehandlingBenyttNyesteKravgrunnlagData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/kravgrunnlag/benytt-nyeste';
};

export type BehandlingBenyttNyesteKravgrunnlagErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingBenyttNyesteKravgrunnlagError =
    BehandlingBenyttNyesteKravgrunnlagErrors[keyof BehandlingBenyttNyesteKravgrunnlagErrors];

export type BehandlingBenyttNyesteKravgrunnlagResponses = {
    /**
     * The request has succeeded.
     */
    200: unknown;
};

export type BehandlingHentVarselbrevTeksterData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/varselbrev/tekster';
};

export type BehandlingHentVarselbrevTeksterErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingHentVarselbrevTeksterError =
    BehandlingHentVarselbrevTeksterErrors[keyof BehandlingHentVarselbrevTeksterErrors];

export type BehandlingHentVarselbrevTeksterResponses = {
    /**
     * The request has succeeded.
     */
    200: VarselbrevTekst;
};

export type BehandlingHentVarselbrevTeksterResponse =
    BehandlingHentVarselbrevTeksterResponses[keyof BehandlingHentVarselbrevTeksterResponses];

export type BehandlingHentVedtaksbrevData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/vedtak/brev';
};

export type BehandlingHentVedtaksbrevErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingHentVedtaksbrevError =
    BehandlingHentVedtaksbrevErrors[keyof BehandlingHentVedtaksbrevErrors];

export type BehandlingHentVedtaksbrevResponses = {
    /**
     * The request has succeeded.
     */
    200: VedtaksbrevData;
};

export type BehandlingHentVedtaksbrevResponse =
    BehandlingHentVedtaksbrevResponses[keyof BehandlingHentVedtaksbrevResponses];

export type BehandlingOppdaterVedtaksbrevData = {
    body: VedtaksbrevRedigerbareDataUpdate;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/vedtak/brev';
};

export type BehandlingOppdaterVedtaksbrevErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingOppdaterVedtaksbrevError =
    BehandlingOppdaterVedtaksbrevErrors[keyof BehandlingOppdaterVedtaksbrevErrors];

export type BehandlingOppdaterVedtaksbrevResponses = {
    /**
     * The request has succeeded.
     */
    200: VedtaksbrevRedigerbareData;
};

export type BehandlingOppdaterVedtaksbrevResponse =
    BehandlingOppdaterVedtaksbrevResponses[keyof BehandlingOppdaterVedtaksbrevResponses];

export type BehandlingHentVedtaksresultatData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/vedtak/resultat';
};

export type BehandlingHentVedtaksresultatErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingHentVedtaksresultatError =
    BehandlingHentVedtaksresultatErrors[keyof BehandlingHentVedtaksresultatErrors];

export type BehandlingHentVedtaksresultatResponses = {
    /**
     * The request has succeeded.
     */
    200: Beregningsresultat;
};

export type BehandlingHentVedtaksresultatResponse =
    BehandlingHentVedtaksresultatResponses[keyof BehandlingHentVedtaksresultatResponses];

export type BehandlingVilkaarsvurderingData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/vilkårsvurdering';
};

export type BehandlingVilkaarsvurderingErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingVilkaarsvurderingError =
    BehandlingVilkaarsvurderingErrors[keyof BehandlingVilkaarsvurderingErrors];

export type BehandlingVilkaarsvurderingResponses = {
    /**
     * The request has succeeded.
     */
    200: Vilkaar;
};

export type BehandlingVilkaarsvurderingResponse =
    BehandlingVilkaarsvurderingResponses[keyof BehandlingVilkaarsvurderingResponses];

export type BehandlingLagreVilkaarsvurderingData = {
    body: VilkaarsvurderingWritable;
    path: {
        behandlingId: string;
        periodeId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/vilkårsvurdering/periode/{periodeId}';
};

export type BehandlingLagreVilkaarsvurderingErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingLagreVilkaarsvurderingError =
    BehandlingLagreVilkaarsvurderingErrors[keyof BehandlingLagreVilkaarsvurderingErrors];

export type BehandlingLagreVilkaarsvurderingResponses = {
    /**
     * The request has succeeded.
     */
    200: Vilkaarsvurdering;
};

export type BehandlingLagreVilkaarsvurderingResponse =
    BehandlingLagreVilkaarsvurderingResponses[keyof BehandlingLagreVilkaarsvurderingResponses];

export type BehandlingVilkaarsvurderingsperioderData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/vilkårsvurdering/perioder';
};

export type BehandlingVilkaarsvurderingsperioderErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingVilkaarsvurderingsperioderError =
    BehandlingVilkaarsvurderingsperioderErrors[keyof BehandlingVilkaarsvurderingsperioderErrors];

export type BehandlingVilkaarsvurderingsperioderResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<PeriodeInfo>;
};

export type BehandlingVilkaarsvurderingsperioderResponse =
    BehandlingVilkaarsvurderingsperioderResponses[keyof BehandlingVilkaarsvurderingsperioderResponses];

export type BehandlingSlaaSammenPerioderData = {
    body: Sammenslaaing;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/vilkårsvurdering/sammenslå';
};

export type BehandlingSlaaSammenPerioderErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingSlaaSammenPerioderError =
    BehandlingSlaaSammenPerioderErrors[keyof BehandlingSlaaSammenPerioderErrors];

export type BehandlingSlaaSammenPerioderResponses = {
    /**
     * The request has succeeded.
     */
    200: unknown;
};

export type BehandlingSplittPeriodeData = {
    body: SplittPeriode;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/vilkårsvurdering/splitt';
};

export type BehandlingSplittPeriodeErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingSplittPeriodeError =
    BehandlingSplittPeriodeErrors[keyof BehandlingSplittPeriodeErrors];

export type BehandlingSplittPeriodeResponses = {
    /**
     * The request has succeeded.
     */
    200: unknown;
};

export type BehandlingHentDokumentInfoData = {
    body?: never;
    path: {
        behandlingId: string;
        dokumentType: DokumentType;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/{dokumentType}/gjeldende';
};

export type BehandlingHentDokumentInfoErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: Error;
    /**
     * Server error
     */
    500: Error;
};

export type BehandlingHentDokumentInfoError =
    BehandlingHentDokumentInfoErrors[keyof BehandlingHentDokumentInfoErrors];

export type BehandlingHentDokumentInfoResponses = {
    /**
     * The request has succeeded.
     */
    200: DokumentInfo;
};

export type BehandlingHentDokumentInfoResponse =
    BehandlingHentDokumentInfoResponses[keyof BehandlingHentDokumentInfoResponses];

export type BrevLagSvgVarselbrevData = {
    body: VarselbrevData;
    path?: never;
    query?: never;
    url: '/api/v1/brev/varselbrev/svg';
};

export type BrevLagSvgVarselbrevResponses = {
    /**
     * The request has succeeded.
     */
    200: Blob | File;
};

export type BrevLagSvgVarselbrevResponse =
    BrevLagSvgVarselbrevResponses[keyof BrevLagSvgVarselbrevResponses];

export type BrevLagSvgVedtaksbrevData = {
    body: VedtaksbrevDataWritable;
    path?: never;
    query?: never;
    url: '/api/v1/brev/vedtaksbrev/svg';
};

export type BrevLagSvgVedtaksbrevResponses = {
    /**
     * The request has succeeded.
     */
    200: Blob | File;
};

export type BrevLagSvgVedtaksbrevResponse =
    BrevLagSvgVedtaksbrevResponses[keyof BrevLagSvgVedtaksbrevResponses];
