// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zBeregningsresultatVurdering = z.enum([
    'GodTro',
    'Forsett',
    'Uaktsomhet',
    'GrovUaktsomhet',
    'BurdeForstått',
    'Forstod',
]);

export const zBeregningsresultatsperiode = z.object({
    fom: z.iso.date(),
    tom: z.iso.date(),
    feilutbetaltBeløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
    vurdering: zBeregningsresultatVurdering,
    andelAvBeløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
        .nullable(),
    renteprosent: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
        .nullable(),
    tilbakekrevingsbeløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
    tilbakekrevesBeløpEtterSkatt: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
});

export const zBestemmelseEllerGrunnlag = z.object({
    nøkkel: z.string(),
    beskrivelse: z.string(),
});

export const zBrevmottaker = z.object({
    navn: z.string(),
    personIdent: z.string(),
});

export const zDokumentInfo = z.object({
    journalpostId: z.string().nullable(),
    dokumentId: z.string().nullable(),
});

export const zDokumentType = z.enum(['VARSELBREV', 'VEDTAKSBREV']);

export const zError = z.object({
    tittel: z.string(),
    melding: z.string(),
});

export const zFakta = z.object({
    rettsligGrunnlag: z.array(z.string()),
});

export const zForhaandsvarselInfo = z.object({
    tekstFraSaksbehandler: z.string(),
    varselbrevSendtTid: z.iso.date(),
});

export const zForsettlig = z.object({
    begrunnelse: z.string(),
});

export const zForstoEllerBurdeForstaatt = z.record(z.string(), z.unknown());

export const zFritekst = z.string().min(3).max(3000);

export const zIkkeVurdert = z.record(z.string(), z.unknown());

export const zIngenting = z.object({
    begrunnelse: z.string(),
});

export const zLogginnslag = z.object({
    behandlingId: z.string(),
    opprettetTid: z.iso.datetime(),
    type: z.string(),
    aktør: z.string(),
    aktørIdent: z.string(),
    tittel: z.string(),
    tekst: z.string().nullable(),
    steg: z.string().nullable(),
    ekstraInfo: z.record(z.string(), z.unknown()),
});

export const zMoment = z.object({
    moment: z.string(),
    beskrivelse: z.string().readonly(),
});

export const zJaSaerligeGrunner = z.object({
    særligeGrunnerFor: z.array(zMoment),
    prosentReduksjon: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint8 to be >= 0' })
        .max(255, { error: 'Invalid value: Expected uint8 to be <= 255' }),
    begrunnelse: z.string(),
    annetBegrunnelse: z.string().nullable(),
});

export const zMuligeRettsligGrunnlag = z.object({
    bestemmelse: zBestemmelseEllerGrunnlag,
    grunnlag: z.array(zBestemmelseEllerGrunnlag),
});

export const zNeiSaerligeGrunner = z.object({
    særligeGrunnerMot: z.array(zMoment),
    begrunnelse: z.string(),
    annetBegrunnelse: z.string().nullable(),
});

export const zOppsummertPeriode = z.object({
    fom: z.string(),
    tom: z.string(),
    feilutbetaltBeløp: z.string(),
    vurdering: z.string(),
    andelAvBeløp: z.string(),
    renteprosent: z.string(),
    tilbakekrevingsbeløp: z.string(),
    tilbakekrevesBeløpEtterSkatt: z.string(),
});

export const zOppsummeringsdata = z.object({
    beregnerSkatt: z.boolean(),
    perioder: z.array(zOppsummertPeriode),
    sumFeilutbetaltBeløp: z.string(),
    sumTilbakekrevesBeløpEtterSkatt: z.string(),
});

export const zPeriode = z.object({
    fom: z.iso.date(),
    tom: z.iso.date(),
});

export const zPeriodeInfo = z.object({
    periodeId: z.uuid(),
    periode: zPeriode,
});

export const zRentekstElement = z.object({
    tekst: z.string().min(3).max(3000),
});

export const zElement = z
    .object({
        type: z.literal('rentekst'),
    })
    .and(zRentekstElement);

export const zPakrevdBegrunnelse = z.object({
    tittel: z.string(),
    forklaring: z.string().readonly(),
    meldingerTilSaksbehandler: z.array(z.string()).readonly(),
    begrunnelseType: z.string(),
    underavsnitt: z.array(zElement),
});

export const zPakrevdBegrunnelseUpdateItem = z.object({
    begrunnelseType: z.string(),
    underavsnitt: z.array(zElement),
});

export const zRettsligGrunnlag = z.object({
    bestemmelse: z.string().min(1),
    grunnlag: z.string().min(1),
});

export const zFaktaPeriode = z.object({
    id: z.string(),
    fom: z.iso.date(),
    tom: z.iso.date(),
    feilutbetaltBeløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
    splittbarePerioder: z.array(
        z.object({
            id: z.string(),
            fom: z.iso.date(),
            tom: z.iso.date(),
            feilutbetaltBeløp: z
                .int()
                .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
                .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
            rettsligGrunnlag: z.array(zRettsligGrunnlag),
        })
    ),
    rettsligGrunnlag: z.array(zRettsligGrunnlag),
});

export const zOppdaterFaktaPeriode = z.object({
    id: z.string(),
    rettsligGrunnlag: z.array(zRettsligGrunnlag).min(1),
});

export const zSaerligeGrunner = z.discriminatedUnion('erDetSaerligeGrunner', [
    zNeiSaerligeGrunner.extend({ erDetSaerligeGrunner: z.literal('nei') }),
    zJaSaerligeGrunner.extend({ erDetSaerligeGrunner: z.literal('ja') }),
]);

export const zGrovtUaktsomt = z.object({
    begrunnelse: z.string(),
    erDetSærligeGrunner: zSaerligeGrunner,
});

export const zSammenslaaing = z.object({
    vilkårsvurderingId: z.uuid(),
    slåesSammenMedId: z.uuid(),
});

export const zSendForhaandsvarsel = z.object({
    tekstFraSaksbehandler: z.string(),
});

export const zSignatur = z.object({
    enhetNavn: z.string(),
    ansvarligSaksbehandler: z.string(),
    besluttendeSaksbehandler: z.string().nullable(),
});

export const zSkalIkkeReduseres = z.object({
    relevans: z.array(zMoment),
    annetBegrunnelse: z.string().nullable(),
    begrunnelse: z.string(),
});

export const zSkalIkkeUnnlates = z.object({
    begrunnelse: z.string(),
    erDetSærligeGrunner: zSaerligeGrunner,
});

export const zSkalReduseres = z.object({
    beløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
    relevans: z.array(zMoment),
    annetBegrunnelse: z.string().nullable(),
    begrunnelse: z.string(),
});

export const zReduksjon = z.discriminatedUnion('reduksjon', [
    zSkalReduseres.extend({ reduksjon: z.literal('skalReduseres') }),
    zSkalIkkeReduseres.extend({ reduksjon: z.literal('skalIkkeReduseres') }),
]);

export const zDeler = z.object({
    beløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
    begrunnelse: z.string(),
    reduksjon: zReduksjon,
});

export const zHele = z.object({
    begrunnelse: z.string(),
    reduksjon: zReduksjon,
});

export const zBelopIBehold = z.discriminatedUnion('belopIBehold', [
    zIngenting.extend({ belopIBehold: z.literal('ingenting') }),
    zHele.extend({ belopIBehold: z.literal('hele') }),
    zDeler.extend({ belopIBehold: z.literal('deler') }),
]);

export const zGodTro = z.object({
    begrunnelse: z.string(),
    beløpIBehold: zBelopIBehold,
});

export const zSkalUnnlates = z.object({
    begrunnelse: z.string(),
});

export const zSplittPeriode = z.object({
    vilkårsvurderingId: z.uuid(),
});

export const zStandardtekst = z.object({
    tittel: z.string(),
    underavsnitt: z.array(zElement),
});

export const zUnderavsnittElement = z.object({
    tittel: z.string(),
    underavsnitt: z.array(zElement),
});

export const zRotElement = z.discriminatedUnion('type', [
    zRentekstElement.extend({ type: z.literal('rentekst') }),
    zUnderavsnittElement.extend({ type: z.literal('underavsnitt') }),
    zPakrevdBegrunnelse.extend({ type: z.literal('påkrevd_begrunnelse') }),
]);

export const zAvsnitt = z.object({
    tittel: z.string().min(3).max(300),
    forklaring: z.string().readonly(),
    meldingerTilSaksbehandler: z.array(z.string()).readonly(),
    id: z.uuid(),
    underavsnitt: z.array(zRotElement),
});

export const zHovedavsnitt = z.object({
    tittel: z.string().min(3).max(300),
    forklaring: z.string().readonly(),
    underavsnitt: z.array(zRotElement),
    hjemler: z.string(),
});

export const zRotElementUpdateItem = z.discriminatedUnion('type', [
    zRentekstElement.extend({ type: z.literal('rentekst') }),
    zUnderavsnittElement.extend({ type: z.literal('underavsnitt') }),
    zPakrevdBegrunnelseUpdateItem.extend({ type: z.literal('påkrevd_begrunnelse') }),
]);

export const zAvsnittUpdateItem = z.object({
    tittel: z.string().min(3).max(300),
    id: z.uuid(),
    underavsnitt: z.array(zRotElementUpdateItem),
});

export const zHovedavsnittUpdate = z.object({
    tittel: z.string().min(3).max(300),
    underavsnitt: z.array(zRotElementUpdateItem),
});

export const zUnnlatelse = z.discriminatedUnion('unnlatelse', [
    zSkalUnnlates.extend({ unnlatelse: z.literal('skalUnnlates') }),
    zSkalIkkeUnnlates.extend({ unnlatelse: z.literal('skalIkkeUnnlates') }),
]);

export const zUaktsomt = z.object({
    begrunnelse: z.string(),
    unnlatelse: zUnnlatelse,
});

export const zAktsomhet = z.discriminatedUnion('aktsomhet', [
    zUaktsomt.extend({ aktsomhet: z.literal('uaktsomt') }),
    zGrovtUaktsomt.extend({ aktsomhet: z.literal('grovtUaktsomt') }),
    zForsettlig.extend({ aktsomhet: z.literal('forsettlig') }),
]);

export const zForaarsaketAvMottaker = z.object({
    begrunnelse: z.string(),
    aktsomhet: zAktsomhet,
});

export const zUpdateUttalelsesfrist = z.object({
    nyFrist: z.iso.date().optional(),
    begrunnelse: z.string().optional(),
});

export const zUttalelseVurdering = z.enum([
    'JA_ETTER_FORHÅNDSVARSEL',
    'NEI_ETTER_FORHÅNDSVARSEL',
    'UNNTAK_ALLEREDE_UTTALT_SEG',
    'UNNTAK_INGEN_UTTALELSE',
    'IKKE_VURDERT',
]);

export const zUttalelse = z.object({
    harBrukerUttaltSeg: zUttalelseVurdering,
    uttalelsesdato: z.iso.date().optional(),
    hvorBrukerenUttalteSeg: z.string().optional(),
    beskrivelse: z.string().optional(),
});

export const zUttalelsesfrist = z.object({
    nyFrist: z.iso.date().optional(),
    begrunnelse: z.string().optional(),
    opprinneligFrist: z.iso.date().readonly(),
});

export const zForhaandsvarselErSendt = z.object({
    forhåndsvarselInfo: zForhaandsvarselInfo,
    uttalelsesfrist: zUttalelsesfrist,
});

export const zVarslingsunntak = z.enum([
    'IKKE_PRAKTISK_MULIG',
    'UKJENT_ADRESSE_ELLER_URIMELIG_ETTERSPORING',
    'ÅPENBART_UNØDVENDIG',
    'ALLEREDE_UTTALET_SEG',
]);

export const zForhaandsvarselUnntak = z.object({
    begrunnelseForUnntak: zVarslingsunntak,
    beskrivelse: z.string(),
});

export const zForhaandsvarselSteg = z.union([
    z
        .object({
            type: z.literal('ikke_vurdert'),
        })
        .and(zIkkeVurdert),
    z
        .object({
            type: z.literal('sendt'),
        })
        .and(zForhaandsvarselErSendt),
    z
        .object({
            type: z.literal('unntak'),
        })
        .and(zForhaandsvarselUnntak),
]);

export const zForhaandsvarselResponse = z.object({
    forhaandsvarselSteg: zForhaandsvarselSteg,
    brukeruttalelse: zUttalelse.nullable(),
});

export const zUnntak = z.object({
    begrunnelseForUnntak: zVarslingsunntak,
    beskrivelse: z.string(),
});

export const zVedtaksbrevRedigerbareData = z.object({
    hovedavsnitt: zHovedavsnitt,
    avsnitt: z.array(zAvsnitt),
    sistOppdatert: z.iso.datetime().readonly(),
});

export const zVedtaksbrevRedigerbareDataUpdate = z.object({
    hovedavsnitt: zHovedavsnittUpdate,
    avsnitt: z.array(zAvsnittUpdateItem),
});

export const zVedtaksresultat = z.enum([
    'IngenTilbakebetaling',
    'DelvisTilbakebetaling',
    'FullTilbakebetaling',
]);

export const zBeregningsresultat = z.object({
    beregningsresultatsperioder: z.array(zBeregningsresultatsperiode),
    vedtaksresultat: zVedtaksresultat,
});

export const zVilkaarsvurderingIkkeVurdert = z.record(z.string(), z.unknown());

export const zVilkaarsvurderingValg = z.union([
    z
        .object({
            vurdering: z.literal('god_tro'),
        })
        .and(zGodTro),
    z
        .object({
            vurdering: z.literal('forårsaket_av_mottaker'),
        })
        .and(zForaarsaketAvMottaker),
    z
        .object({
            vurdering: z.literal('forsto_eller_burde_forstått'),
        })
        .and(zForstoEllerBurdeForstaatt),
    z
        .object({
            vurdering: z.literal('ikke_vurdert'),
        })
        .and(zVilkaarsvurderingIkkeVurdert),
]);

export const zVilkaarsvurdering = z.object({
    id: z.uuid(),
    periode: zPeriode.readonly(),
    delbarePerioder: z.array(zPeriodeInfo).readonly(),
    valg: zVilkaarsvurderingValg,
});

export const zYtelse = z.object({
    url: z.string(),
    ubestemtEntall: z.string(),
    bestemtEntall: z.string(),
});

export const zVedtaksbrevData = z.object({
    hovedavsnitt: zHovedavsnitt,
    avsnitt: z.array(zAvsnitt),
    sistOppdatert: z.iso.datetime().readonly(),
    brevGjelder: zBrevmottaker,
    sendtDato: z.string(),
    ytelse: zYtelse,
    signatur: zSignatur,
    oppsummeringstabell: zOppsummeringsdata,
    bunntekster: z.array(zStandardtekst),
    saksnummer: z.string(),
});

export const zAvEnum = z.enum(['NAV', 'BRUKER', 'IKKE_VURDERT']);

export const zOppdaget = z.object({
    dato: z.iso.date().nullable(),
    av: zAvEnum,
    beskrivelse: zFritekst.nullable(),
});

export const zVurdering = z.object({
    årsak: zFritekst.nullable(),
    oppdaget: zOppdaget.optional(),
});

export const zOppdaterFaktaOmFeilutbetaling = z.object({
    perioder: z.array(zOppdaterFaktaPeriode).optional(),
    vurdering: zVurdering.optional(),
});

export const zResultatEnum = z.enum(['INNVILGET', 'OPPHØRT']);

export const zRevurdering = z.object({
    årsak: z.string(),
    vedtaksdato: z.iso.date(),
    resultat: zResultatEnum,
});

export const zFeilutbetaling = z.object({
    beløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
    fom: z.iso.date(),
    tom: z.iso.date(),
    revurdering: zRevurdering,
});

export const zFaktaOmFeilutbetaling = z.object({
    feilutbetaling: zFeilutbetaling,
    tidligereVarsletBeløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
        .nullable(),
    muligeRettsligGrunnlag: z.array(zMuligeRettsligGrunnlag),
    perioder: z.array(zFaktaPeriode),
    vurdering: zVurdering,
    ferdigvurdert: z.boolean(),
});

export const z0Enum = z.enum([
    'FULL_TILBAKEKREVING',
    'INGEN_TILBAKEKREVING',
    'DELVIS_TILBAKEKREVING',
]);

export const zVilkaarsperiode = z.object({
    feilutbetaltBeløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
        .readonly(),
    delresultat: z0Enum.nullable(),
    fakta: zFakta.readonly(),
    simulertBeløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
        .readonly(),
    vilkårsvurdering: zVilkaarsvurdering,
});

export const zVilkaar = z.object({
    vilkårsperioder: z.array(zVilkaarsperiode),
    ferdigvurdert: z.boolean().readonly(),
    momenterSærligeGrunner: z.array(zMoment).readonly(),
    momenterReduksjonGodTro: z.array(zMoment).readonly(),
});

export const zMomentWritable = z.object({
    moment: z.string(),
});

export const zJaSaerligeGrunnerWritable = z.object({
    særligeGrunnerFor: z.array(zMomentWritable),
    prosentReduksjon: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint8 to be >= 0' })
        .max(255, { error: 'Invalid value: Expected uint8 to be <= 255' }),
    begrunnelse: z.string(),
    annetBegrunnelse: z.string().nullable(),
});

export const zNeiSaerligeGrunnerWritable = z.object({
    særligeGrunnerMot: z.array(zMomentWritable),
    begrunnelse: z.string(),
    annetBegrunnelse: z.string().nullable(),
});

export const zPakrevdBegrunnelseWritable = z.object({
    tittel: z.string(),
    begrunnelseType: z.string(),
    underavsnitt: z.array(zElement),
});

export const zRotElementWritable = z.discriminatedUnion('type', [
    zRentekstElement.extend({ type: z.literal('rentekst') }),
    zUnderavsnittElement.extend({ type: z.literal('underavsnitt') }),
    zPakrevdBegrunnelseWritable.extend({ type: z.literal('påkrevd_begrunnelse') }),
]);

export const zAvsnittWritable = z.object({
    tittel: z.string().min(3).max(300),
    id: z.uuid(),
    underavsnitt: z.array(zRotElementWritable),
});

export const zHovedavsnittWritable = z.object({
    tittel: z.string().min(3).max(300),
    underavsnitt: z.array(zRotElementWritable),
    hjemler: z.string(),
});

export const zSaerligeGrunnerWritable = z.discriminatedUnion('erDetSaerligeGrunner', [
    zNeiSaerligeGrunnerWritable.extend({ erDetSaerligeGrunner: z.literal('nei') }),
    zJaSaerligeGrunnerWritable.extend({ erDetSaerligeGrunner: z.literal('ja') }),
]);

export const zGrovtUaktsomtWritable = z.object({
    begrunnelse: z.string(),
    erDetSærligeGrunner: zSaerligeGrunnerWritable,
});

export const zSkalIkkeReduseresWritable = z.object({
    relevans: z.array(zMomentWritable),
    annetBegrunnelse: z.string().nullable(),
    begrunnelse: z.string(),
});

export const zSkalIkkeUnnlatesWritable = z.object({
    begrunnelse: z.string(),
    erDetSærligeGrunner: zSaerligeGrunnerWritable,
});

export const zSkalReduseresWritable = z.object({
    beløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
    relevans: z.array(zMomentWritable),
    annetBegrunnelse: z.string().nullable(),
    begrunnelse: z.string(),
});

export const zReduksjonWritable = z.discriminatedUnion('reduksjon', [
    zSkalReduseresWritable.extend({ reduksjon: z.literal('skalReduseres') }),
    zSkalIkkeReduseresWritable.extend({ reduksjon: z.literal('skalIkkeReduseres') }),
]);

export const zDelerWritable = z.object({
    beløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
    begrunnelse: z.string(),
    reduksjon: zReduksjonWritable,
});

export const zHeleWritable = z.object({
    begrunnelse: z.string(),
    reduksjon: zReduksjonWritable,
});

export const zBelopIBeholdWritable = z.discriminatedUnion('belopIBehold', [
    zIngenting.extend({ belopIBehold: z.literal('ingenting') }),
    zHeleWritable.extend({ belopIBehold: z.literal('hele') }),
    zDelerWritable.extend({ belopIBehold: z.literal('deler') }),
]);

export const zGodTroWritable = z.object({
    begrunnelse: z.string(),
    beløpIBehold: zBelopIBeholdWritable,
});

export const zUnnlatelseWritable = z.discriminatedUnion('unnlatelse', [
    zSkalUnnlates.extend({ unnlatelse: z.literal('skalUnnlates') }),
    zSkalIkkeUnnlatesWritable.extend({ unnlatelse: z.literal('skalIkkeUnnlates') }),
]);

export const zUaktsomtWritable = z.object({
    begrunnelse: z.string(),
    unnlatelse: zUnnlatelseWritable,
});

export const zAktsomhetWritable = z.discriminatedUnion('aktsomhet', [
    zUaktsomtWritable.extend({ aktsomhet: z.literal('uaktsomt') }),
    zGrovtUaktsomtWritable.extend({ aktsomhet: z.literal('grovtUaktsomt') }),
    zForsettlig.extend({ aktsomhet: z.literal('forsettlig') }),
]);

export const zForaarsaketAvMottakerWritable = z.object({
    begrunnelse: z.string(),
    aktsomhet: zAktsomhetWritable,
});

export const zUttalelsesfristWritable = z.object({
    nyFrist: z.iso.date().optional(),
    begrunnelse: z.string().optional(),
});

export const zForhaandsvarselErSendtWritable = z.object({
    forhåndsvarselInfo: zForhaandsvarselInfo,
    uttalelsesfrist: zUttalelsesfristWritable,
});

export const zForhaandsvarselStegWritable = z.union([
    z
        .object({
            type: z.literal('ikke_vurdert'),
        })
        .and(zIkkeVurdert),
    z
        .object({
            type: z.literal('sendt'),
        })
        .and(zForhaandsvarselErSendtWritable),
    z
        .object({
            type: z.literal('unntak'),
        })
        .and(zForhaandsvarselUnntak),
]);

export const zForhaandsvarselResponseWritable = z.object({
    forhaandsvarselSteg: zForhaandsvarselStegWritable,
    brukeruttalelse: zUttalelse.nullable(),
});

export const zVedtaksbrevDataWritable = z.object({
    hovedavsnitt: zHovedavsnittWritable,
    avsnitt: z.array(zAvsnittWritable),
    brevGjelder: zBrevmottaker,
    sendtDato: z.string(),
    ytelse: zYtelse,
    signatur: zSignatur,
    oppsummeringstabell: zOppsummeringsdata,
    bunntekster: z.array(zStandardtekst),
    saksnummer: z.string(),
});

export const zVedtaksbrevRedigerbareDataWritable = z.object({
    hovedavsnitt: zHovedavsnittWritable,
    avsnitt: z.array(zAvsnittWritable),
});

export const zVilkaarsvurderingValgWritable = z.union([
    z
        .object({
            vurdering: z.literal('god_tro'),
        })
        .and(zGodTroWritable),
    z
        .object({
            vurdering: z.literal('forårsaket_av_mottaker'),
        })
        .and(zForaarsaketAvMottakerWritable),
    z
        .object({
            vurdering: z.literal('forsto_eller_burde_forstått'),
        })
        .and(zForstoEllerBurdeForstaatt),
    z
        .object({
            vurdering: z.literal('ikke_vurdert'),
        })
        .and(zVilkaarsvurderingIkkeVurdert),
]);

export const zVilkaarsvurderingWritable = z.object({
    id: z.uuid(),
    valg: zVilkaarsvurderingValgWritable,
});

export const zVilkaarsperiodeWritable = z.object({
    vilkårsvurdering: zVilkaarsvurderingWritable,
});

export const zVilkaarWritable = z.object({
    vilkårsperioder: z.array(zVilkaarsperiodeWritable),
});

export const zBehandlingBehandlingsloggPath = z.object({
    behandlingId: z.uuid(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingBehandlingsloggResponse = z.array(zLogginnslag);

export const zBehandlingFaktaPath = z.object({
    behandlingId: z.string(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingFaktaResponse = zFaktaOmFeilutbetaling;

export const zBehandlingOppdaterFaktaBody = zOppdaterFaktaOmFeilutbetaling;

export const zBehandlingOppdaterFaktaPath = z.object({
    behandlingId: z.string(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingOppdaterFaktaResponse = zFaktaOmFeilutbetaling;

export const zBehandlingForeslaaVedtakPath = z.object({
    behandlingId: z.uuid(),
});

export const zBehandlingForhandsvarselPath = z.object({
    behandlingId: z.uuid(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingForhandsvarselResponse = zForhaandsvarselResponse;

export const zBehandlingSendVarselbrevBody = zSendForhaandsvarsel;

export const zBehandlingSendVarselbrevPath = z.object({
    behandlingId: z.uuid(),
});

export const zBehandlingLagreForhaandsvarselUnntakBody = zUnntak;

export const zBehandlingLagreForhaandsvarselUnntakPath = z.object({
    behandlingId: z.uuid(),
});

export const zBehandlingUtsettUttalelsesfristBody = zUpdateUttalelsesfrist;

export const zBehandlingUtsettUttalelsesfristPath = z.object({
    behandlingId: z.uuid(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingUtsettUttalelsesfristResponse = zUttalelsesfrist;

export const zBehandlingLagreBrukersuttalelseBody = zUttalelse;

export const zBehandlingLagreBrukersuttalelsePath = z.object({
    behandlingId: z.uuid(),
});

export const zBehandlingHentDokumentPath = z.object({
    behandlingId: z.uuid(),
    journalpostId: z.string(),
    dokumentInfoId: z.string(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingHentDokumentResponse = z.string();

export const zBehandlingHentVedtaksbrevPath = z.object({
    behandlingId: z.string(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingHentVedtaksbrevResponse = zVedtaksbrevData;

export const zBehandlingOppdaterVedtaksbrevBody = zVedtaksbrevRedigerbareDataUpdate;

export const zBehandlingOppdaterVedtaksbrevPath = z.object({
    behandlingId: z.uuid(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingOppdaterVedtaksbrevResponse = zVedtaksbrevRedigerbareData;

export const zBehandlingHentVedtaksresultatPath = z.object({
    behandlingId: z.uuid(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingHentVedtaksresultatResponse = zBeregningsresultat;

export const zBehandlingVilkaarsvurderingPath = z.object({
    behandlingId: z.uuid(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingVilkaarsvurderingResponse = zVilkaar;

export const zBehandlingLagreVilkaarsvurderingBody = zVilkaarWritable;

export const zBehandlingLagreVilkaarsvurderingPath = z.object({
    behandlingId: z.uuid(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingLagreVilkaarsvurderingResponse = zVilkaar;

export const zBehandlingVilkaarsvurderingsperioderPath = z.object({
    behandlingId: z.uuid(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingVilkaarsvurderingsperioderResponse = z.array(zPeriodeInfo);

export const zBehandlingSlaaSammenPerioderBody = zSammenslaaing;

export const zBehandlingSlaaSammenPerioderPath = z.object({
    behandlingId: z.uuid(),
});

export const zBehandlingSplittPeriodeBody = zSplittPeriode;

export const zBehandlingSplittPeriodePath = z.object({
    behandlingId: z.uuid(),
});

export const zBehandlingHentDokumentInfoPath = z.object({
    behandlingId: z.uuid(),
    dokumentType: zDokumentType,
});

/**
 * The request has succeeded.
 */
export const zBehandlingHentDokumentInfoResponse = zDokumentInfo;

export const zVedtaksbrevLagSvgVedtaksbrevBody = zVedtaksbrevDataWritable;

/**
 * The request has succeeded.
 */
export const zVedtaksbrevLagSvgVedtaksbrevResponse = z.string();
