// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zBestemmelseEllerGrunnlag = z.object({
    nøkkel: z.string(),
    beskrivelse: z.string(),
});

export const zBrevmottaker = z.object({
    navn: z.string(),
    personIdent: z.string(),
});

export const zError = z.object({
    message: z.string(),
});

export const zFritekst = z.string().min(3).max(3000);

export const zMuligeRettsligGrunnlag = z.object({
    bestemmelse: zBestemmelseEllerGrunnlag,
    grunnlag: z.array(zBestemmelseEllerGrunnlag),
});

export const zRentekstElement = z.object({
    tekst: z.string().min(3).max(3000),
});

export const zElement = z
    .object({
        type: z.literal('rentekst'),
    })
    .and(zRentekstElement);

export const zRettsligGrunnlag = z.object({
    bestemmelse: z.string().min(1),
    grunnlag: z.string().min(1),
});

export const zFaktaPeriode = z.object({
    id: z.string(),
    fom: z.iso.date(),
    tom: z.iso.date(),
    feilutbetaltBeløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
    splittbarePerioder: z.array(
        z.object({
            id: z.string(),
            fom: z.iso.date(),
            tom: z.iso.date(),
            feilutbetaltBeløp: z
                .int()
                .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
                .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
            rettsligGrunnlag: z.array(zRettsligGrunnlag),
        })
    ),
    rettsligGrunnlag: z.array(zRettsligGrunnlag),
});

export const zOppdaterFaktaPeriode = z.object({
    id: z.string(),
    rettsligGrunnlag: z.array(zRettsligGrunnlag).min(1),
});

export const zSignatur = z.object({
    enhetNavn: z.string(),
    ansvarligSaksbehandler: z.string(),
    besluttendeSaksbehandler: z.union([z.string(), z.null()]),
});

export const zUnderavsnittElement = z.object({
    tittel: z.string(),
    underavsnitt: z.array(zElement),
});

export const zRotElement = z.union([
    z
        .object({
            type: z.literal('rentekst'),
        })
        .and(zRentekstElement),
    z
        .object({
            type: z.literal('underavsnitt'),
        })
        .and(zUnderavsnittElement),
]);

export const zAvsnitt = z.object({
    tittel: z.string().min(3).max(300),
    id: z.uuid(),
    underavsnitt: z.array(zRotElement),
});

export const zHovedavsnitt = z.object({
    tittel: z.string().min(3).max(300),
    underavsnitt: z.array(zRotElement),
});

export const zVedtaksbrevRedigerbareData = z.object({
    hovedavsnitt: zHovedavsnitt,
    avsnitt: z.array(zAvsnitt),
    sistOppdatert: z.iso.datetime().readonly(),
});

export const zYtelse = z.object({
    url: z.string(),
    ubestemtEntall: z.string(),
    bestemtEntall: z.string(),
});

export const zVedtaksbrevData = z.object({
    hovedavsnitt: zHovedavsnitt,
    avsnitt: z.array(zAvsnitt),
    sistOppdatert: z.iso.datetime().readonly(),
    brevGjelder: zBrevmottaker,
    sendtDato: z.string(),
    ytelse: zYtelse,
    signatur: zSignatur,
});

export const zAvEnum = z.enum(['NAV', 'BRUKER', 'IKKE_VURDERT']);

export const zOppdaget = z.object({
    dato: z.union([z.iso.date(), z.null()]),
    av: zAvEnum,
    beskrivelse: z.union([zFritekst, z.null()]),
});

export const zVurdering = z.object({
    årsak: z.union([zFritekst, z.null()]),
    oppdaget: z.optional(zOppdaget),
});

export const zOppdaterFaktaOmFeilutbetaling = z.object({
    perioder: z.optional(z.array(zOppdaterFaktaPeriode)),
    vurdering: z.optional(zVurdering),
});

export const zResultatEnum = z.enum(['INNVILGET', 'OPPHØRT']);

export const zRevurdering = z.object({
    årsak: z.string(),
    vedtaksdato: z.iso.date(),
    resultat: zResultatEnum,
});

export const zFeilutbetaling = z.object({
    beløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
    fom: z.iso.date(),
    tom: z.iso.date(),
    revurdering: zRevurdering,
});

export const zFaktaOmFeilutbetaling = z.object({
    feilutbetaling: zFeilutbetaling,
    tidligereVarsletBeløp: z.union([
        z
            .int()
            .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
            .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
        z.null(),
    ]),
    muligeRettsligGrunnlag: z.array(zMuligeRettsligGrunnlag),
    perioder: z.array(zFaktaPeriode),
    vurdering: zVurdering,
    ferdigvurdert: z.boolean(),
});

export const zVedtaksbrevDataWritable = z.object({
    hovedavsnitt: zHovedavsnitt,
    avsnitt: z.array(zAvsnitt),
    brevGjelder: zBrevmottaker,
    sendtDato: z.string(),
    ytelse: zYtelse,
    signatur: zSignatur,
});

export const zVedtaksbrevRedigerbareDataWritable = z.object({
    hovedavsnitt: zHovedavsnitt,
    avsnitt: z.array(zAvsnitt),
});

export const zBehandlingFaktaData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        behandlingId: z.string(),
    }),
    query: z.optional(z.never()),
});

/**
 * The request has succeeded.
 */
export const zBehandlingFaktaResponse = zFaktaOmFeilutbetaling;

export const zBehandlingOppdaterFaktaData = z.object({
    body: zOppdaterFaktaOmFeilutbetaling,
    path: z.object({
        behandlingId: z.string(),
    }),
    query: z.optional(z.never()),
});

/**
 * The request has succeeded.
 */
export const zBehandlingOppdaterFaktaResponse = zFaktaOmFeilutbetaling;

export const zBehandlingHentVedtaksbrevData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        behandlingId: z.string(),
    }),
    query: z.optional(z.never()),
});

/**
 * The request has succeeded.
 */
export const zBehandlingHentVedtaksbrevResponse = zVedtaksbrevData;

export const zBehandlingOppdaterVedtaksbrevData = z.object({
    body: zVedtaksbrevRedigerbareDataWritable,
    path: z.object({
        behandlingId: z.uuid(),
    }),
    query: z.optional(z.never()),
});

/**
 * The request has succeeded.
 */
export const zBehandlingOppdaterVedtaksbrevResponse = zVedtaksbrevRedigerbareData;

export const zVedtaksbrevLagSvgVedtaksbrevData = z.object({
    body: zVedtaksbrevDataWritable,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
