// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zBeregningsresultatVurdering = z.enum([
    'GodTro',
    'Forsett',
    'Uaktsomhet',
    'GrovUaktsomhet',
]);

export const zBeregningsresultatsperiode = z.object({
    fom: z.iso.date(),
    tom: z.iso.date(),
    feilutbetaltBeløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
    vurdering: zBeregningsresultatVurdering,
    andelAvBeløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
        .nullable(),
    renteprosent: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
        .nullable(),
    tilbakekrevingsbeløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
    tilbakekrevesBeløpEtterSkatt: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
});

export const zBestemmelseEllerGrunnlag = z.object({
    nøkkel: z.string(),
    beskrivelse: z.string(),
});

export const zBrevmottaker = z.object({
    navn: z.string(),
    personIdent: z.string(),
});

export const zError = z.object({
    tittel: z.string(),
    melding: z.string(),
});

export const zForhaandsvarselInfo = z.object({
    tekstFraSaksbehandler: z.string(),
    varselbrevSendtTid: z.iso.date(),
});

export const zFritekst = z.string().min(3).max(3000);

export const zIkkeVurdert = z.object({});

export const zLogginnslag = z.object({
    behandlingId: z.string(),
    opprettetTid: z.iso.datetime(),
    type: z.string(),
    aktør: z.string(),
    aktørIdent: z.string(),
    tittel: z.string(),
    tekst: z.string().nullable(),
    steg: z.string().nullable(),
    journalpostId: z.string().nullable(),
    dokumentInfoId: z.string().nullable(),
});

export const zMuligeRettsligGrunnlag = z.object({
    bestemmelse: zBestemmelseEllerGrunnlag,
    grunnlag: z.array(zBestemmelseEllerGrunnlag),
});

export const zOppsummertPeriode = z.object({
    fom: z.string(),
    tom: z.string(),
    feilutbetaltBeløp: z.string(),
    vurdering: z.string(),
    andelAvBeløp: z.string(),
    renteprosent: z.string(),
    tilbakekrevingsbeløp: z.string(),
    tilbakekrevesBeløpEtterSkatt: z.string(),
});

export const zOppsummeringsdata = z.object({
    beregnerSkatt: z.boolean(),
    perioder: z.array(zOppsummertPeriode),
    sumFeilutbetaltBeløp: z.string(),
    sumTilbakekrevesBeløpEtterSkatt: z.string(),
});

export const zRentekstElement = z.object({
    tekst: z.string().min(3).max(3000),
});

export const zElement = z
    .object({
        type: z.literal('rentekst'),
    })
    .and(zRentekstElement);

export const zPakrevdBegrunnelse = z.object({
    tittel: z.string(),
    forklaring: z.string().readonly(),
    meldingerTilSaksbehandler: z.array(z.string()).readonly(),
    begrunnelseType: z.string(),
    underavsnitt: z.array(zElement),
});

export const zPakrevdBegrunnelseUpdateItem = z.object({
    begrunnelseType: z.string(),
    underavsnitt: z.array(zElement),
});

export const zRettsligGrunnlag = z.object({
    bestemmelse: z.string().min(1),
    grunnlag: z.string().min(1),
});

export const zFaktaPeriode = z.object({
    id: z.string(),
    fom: z.iso.date(),
    tom: z.iso.date(),
    feilutbetaltBeløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
    splittbarePerioder: z.array(
        z.object({
            id: z.string(),
            fom: z.iso.date(),
            tom: z.iso.date(),
            feilutbetaltBeløp: z
                .int()
                .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
                .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
            rettsligGrunnlag: z.array(zRettsligGrunnlag),
        })
    ),
    rettsligGrunnlag: z.array(zRettsligGrunnlag),
});

export const zOppdaterFaktaPeriode = z.object({
    id: z.string(),
    rettsligGrunnlag: z.array(zRettsligGrunnlag).min(1),
});

export const zSendForhaandsvarsel = z.object({
    tekstFraSaksbehandler: z.string(),
});

export const zSignatur = z.object({
    enhetNavn: z.string(),
    ansvarligSaksbehandler: z.string(),
    besluttendeSaksbehandler: z.string().nullable(),
});

export const zStandardtekst = z.object({
    tittel: z.string(),
    underavsnitt: z.array(zElement),
});

export const zUnderavsnittElement = z.object({
    tittel: z.string(),
    underavsnitt: z.array(zElement),
});

export const zRotElement = z.discriminatedUnion('type', [
    zRentekstElement.extend({ type: z.literal('rentekst') }),
    zUnderavsnittElement.extend({ type: z.literal('underavsnitt') }),
    zPakrevdBegrunnelse.extend({ type: z.literal('påkrevd_begrunnelse') }),
]);

export const zAvsnitt = z.object({
    tittel: z.string().min(3).max(300),
    forklaring: z.string().readonly(),
    meldingerTilSaksbehandler: z.array(z.string()).readonly(),
    id: z.uuid(),
    underavsnitt: z.array(zRotElement),
});

export const zHovedavsnitt = z.object({
    tittel: z.string().min(3).max(300),
    forklaring: z.string().readonly(),
    underavsnitt: z.array(zRotElement),
    hjemler: z.string(),
});

export const zRotElementUpdateItem = z.discriminatedUnion('type', [
    zRentekstElement.extend({ type: z.literal('rentekst') }),
    zUnderavsnittElement.extend({ type: z.literal('underavsnitt') }),
    zPakrevdBegrunnelseUpdateItem.extend({ type: z.literal('påkrevd_begrunnelse') }),
]);

export const zAvsnittUpdateItem = z.object({
    tittel: z.string().min(3).max(300),
    id: z.uuid(),
    underavsnitt: z.array(zRotElementUpdateItem),
});

export const zHovedavsnittUpdate = z.object({
    tittel: z.string().min(3).max(300),
    underavsnitt: z.array(zRotElementUpdateItem),
});

export const zUpdateUttalelsesfrist = z.object({
    nyFrist: z.iso.date().optional(),
    begrunnelse: z.string().optional(),
});

export const zUttalelseVurdering = z.enum([
    'JA_ETTER_FORHÅNDSVARSEL',
    'NEI_ETTER_FORHÅNDSVARSEL',
    'UNNTAK_ALLEREDE_UTTALT_SEG',
    'UNNTAK_INGEN_UTTALELSE',
    'IKKE_VURDERT',
]);

export const zUttalelse = z.object({
    harBrukerUttaltSeg: zUttalelseVurdering,
    uttalelsesdato: z.iso.date().optional(),
    hvorBrukerenUttalteSeg: z.string().optional(),
    beskrivelse: z.string().optional(),
});

export const zUttalelsesfrist = z.object({
    nyFrist: z.iso.date().optional(),
    begrunnelse: z.string().optional(),
    opprinneligFrist: z.iso.date().readonly(),
});

export const zForhaandsvarselErSendt = z.object({
    forhåndsvarselInfo: zForhaandsvarselInfo,
    uttalelsesfrist: zUttalelsesfrist,
});

export const zVarslingsunntak = z.enum([
    'IKKE_PRAKTISK_MULIG',
    'UKJENT_ADRESSE_ELLER_URIMELIG_ETTERSPORING',
    'ÅPENBART_UNØDVENDIG',
    'ALLEREDE_UTTALET_SEG',
]);

export const zForhaandsvarselUnntak = z.object({
    begrunnelseForUnntak: zVarslingsunntak,
    beskrivelse: z.string(),
});

export const zForhaandsvarselSteg = z.discriminatedUnion('type', [
    zIkkeVurdert.extend({ type: z.literal('ikke_vurdert') }),
    zForhaandsvarselErSendt.extend({ type: z.literal('sendt') }),
    zForhaandsvarselUnntak.extend({ type: z.literal('unntak') }),
]);

export const zForhaandsvarselResponse = z.object({
    forhaandsvarselSteg: zForhaandsvarselSteg,
    brukeruttalelse: zUttalelse.nullable(),
});

export const zVedtaksbrevRedigerbareData = z.object({
    hovedavsnitt: zHovedavsnitt,
    avsnitt: z.array(zAvsnitt),
    sistOppdatert: z.iso.datetime().readonly(),
});

export const zVedtaksbrevRedigerbareDataUpdate = z.object({
    hovedavsnitt: zHovedavsnittUpdate,
    avsnitt: z.array(zAvsnittUpdateItem),
});

export const zVedtaksresultat = z.enum([
    'IngenTilbakebetaling',
    'DelvisTilbakebetaling',
    'FullTilbakebetaling',
]);

export const zBeregningsresultat = z.object({
    beregningsresultatsperioder: z.array(zBeregningsresultatsperiode),
    vedtaksresultat: zVedtaksresultat,
});

export const zYtelse = z.object({
    url: z.string(),
    ubestemtEntall: z.string(),
    bestemtEntall: z.string(),
});

export const zVedtaksbrevData = z.object({
    hovedavsnitt: zHovedavsnitt,
    avsnitt: z.array(zAvsnitt),
    sistOppdatert: z.iso.datetime().readonly(),
    brevGjelder: zBrevmottaker,
    sendtDato: z.string(),
    ytelse: zYtelse,
    signatur: zSignatur,
    oppsummeringstabell: zOppsummeringsdata,
    bunntekster: z.array(zStandardtekst),
    saksnummer: z.string(),
});

export const zAvEnum = z.enum(['NAV', 'BRUKER', 'IKKE_VURDERT']);

export const zOppdaget = z.object({
    dato: z.iso.date().nullable(),
    av: zAvEnum,
    beskrivelse: zFritekst.nullable(),
});

export const zVurdering = z.object({
    årsak: zFritekst.nullable(),
    oppdaget: zOppdaget.optional(),
});

export const zOppdaterFaktaOmFeilutbetaling = z.object({
    perioder: z.array(zOppdaterFaktaPeriode).optional(),
    vurdering: zVurdering.optional(),
});

export const zResultatEnum = z.enum(['INNVILGET', 'OPPHØRT']);

export const zRevurdering = z.object({
    årsak: z.string(),
    vedtaksdato: z.iso.date(),
    resultat: zResultatEnum,
});

export const zFeilutbetaling = z.object({
    beløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
    fom: z.iso.date(),
    tom: z.iso.date(),
    revurdering: zRevurdering,
});

export const zFaktaOmFeilutbetaling = z.object({
    feilutbetaling: zFeilutbetaling,
    tidligereVarsletBeløp: z
        .int()
        .min(0, { error: 'Invalid value: Expected uint32 to be >= 0' })
        .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
        .nullable(),
    muligeRettsligGrunnlag: z.array(zMuligeRettsligGrunnlag),
    perioder: z.array(zFaktaPeriode),
    vurdering: zVurdering,
    ferdigvurdert: z.boolean(),
});

export const zPakrevdBegrunnelseWritable = z.object({
    tittel: z.string(),
    begrunnelseType: z.string(),
    underavsnitt: z.array(zElement),
});

export const zRotElementWritable = z.discriminatedUnion('type', [
    zRentekstElement.extend({ type: z.literal('rentekst') }),
    zUnderavsnittElement.extend({ type: z.literal('underavsnitt') }),
    zPakrevdBegrunnelseWritable.extend({ type: z.literal('påkrevd_begrunnelse') }),
]);

export const zAvsnittWritable = z.object({
    tittel: z.string().min(3).max(300),
    id: z.uuid(),
    underavsnitt: z.array(zRotElementWritable),
});

export const zHovedavsnittWritable = z.object({
    tittel: z.string().min(3).max(300),
    underavsnitt: z.array(zRotElementWritable),
    hjemler: z.string(),
});

export const zUttalelsesfristWritable = z.object({
    nyFrist: z.iso.date().optional(),
    begrunnelse: z.string().optional(),
});

export const zForhaandsvarselErSendtWritable = z.object({
    forhåndsvarselInfo: zForhaandsvarselInfo,
    uttalelsesfrist: zUttalelsesfristWritable,
});

export const zForhaandsvarselStegWritable = z.discriminatedUnion('type', [
    zIkkeVurdert.extend({ type: z.literal('ikke_vurdert') }),
    zForhaandsvarselErSendtWritable.extend({ type: z.literal('sendt') }),
    zForhaandsvarselUnntak.extend({ type: z.literal('unntak') }),
]);

export const zForhaandsvarselResponseWritable = z.object({
    forhaandsvarselSteg: zForhaandsvarselStegWritable,
    brukeruttalelse: zUttalelse.nullable(),
});

export const zVedtaksbrevDataWritable = z.object({
    hovedavsnitt: zHovedavsnittWritable,
    avsnitt: z.array(zAvsnittWritable),
    brevGjelder: zBrevmottaker,
    sendtDato: z.string(),
    ytelse: zYtelse,
    signatur: zSignatur,
    oppsummeringstabell: zOppsummeringsdata,
    bunntekster: z.array(zStandardtekst),
    saksnummer: z.string(),
});

export const zVedtaksbrevRedigerbareDataWritable = z.object({
    hovedavsnitt: zHovedavsnittWritable,
    avsnitt: z.array(zAvsnittWritable),
});

export const zBehandlingBehandlingsloggPath = z.object({
    behandlingId: z.uuid(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingBehandlingsloggResponse = z.array(zLogginnslag);

export const zBehandlingFaktaPath = z.object({
    behandlingId: z.string(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingFaktaResponse = zFaktaOmFeilutbetaling;

export const zBehandlingOppdaterFaktaBody = zOppdaterFaktaOmFeilutbetaling;

export const zBehandlingOppdaterFaktaPath = z.object({
    behandlingId: z.string(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingOppdaterFaktaResponse = zFaktaOmFeilutbetaling;

export const zBehandlingForeslaaVedtakPath = z.object({
    behandlingId: z.uuid(),
});

export const zBehandlingForhandsvarselPath = z.object({
    behandlingId: z.uuid(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingForhandsvarselResponse = zForhaandsvarselResponse;

export const zBehandlingSendVarselbrevBody = zSendForhaandsvarsel;

export const zBehandlingSendVarselbrevPath = z.object({
    behandlingId: z.uuid(),
});

export const zBehandlingLagreForhaandsvarselUnntakBody = zForhaandsvarselUnntak;

export const zBehandlingLagreForhaandsvarselUnntakPath = z.object({
    behandlingId: z.uuid(),
});

export const zBehandlingUtsettUttalelsesfristBody = zUpdateUttalelsesfrist;

export const zBehandlingUtsettUttalelsesfristPath = z.object({
    behandlingId: z.uuid(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingUtsettUttalelsesfristResponse = zUttalelsesfrist;

export const zBehandlingLagreBrukersuttalelseBody = zUttalelse;

export const zBehandlingLagreBrukersuttalelsePath = z.object({
    behandlingId: z.uuid(),
});

export const zBehandlingHentVedtaksbrevPath = z.object({
    behandlingId: z.string(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingHentVedtaksbrevResponse = zVedtaksbrevData;

export const zBehandlingOppdaterVedtaksbrevBody = zVedtaksbrevRedigerbareDataUpdate;

export const zBehandlingOppdaterVedtaksbrevPath = z.object({
    behandlingId: z.uuid(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingOppdaterVedtaksbrevResponse = zVedtaksbrevRedigerbareData;

export const zBehandlingHentVedtaksresultatPath = z.object({
    behandlingId: z.uuid(),
});

/**
 * The request has succeeded.
 */
export const zBehandlingHentVedtaksresultatResponse = zBeregningsresultat;

export const zVedtaksbrevLagSvgVedtaksbrevBody = zVedtaksbrevDataWritable;

/**
 * The request has succeeded.
 */
export const zVedtaksbrevLagSvgVedtaksbrevResponse = z.string();
