apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tilbakekreving-frontend
  namespace: tilbake
  labels:
    team: tilbake
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://tilbakekreving.intern.dev.nav.no
    - https://tilbakekreving.ansatt.dev.nav.no
  vault:
    enabled: false
  azure:
    application:
      claims:
        groups:
          - id: d21e00a4-969d-4b28-8782-dc818abfae65 # 0000-GA-Barnetrygd
          - id: 9449c153-5a1e-44a7-84c6-7cc7a8867233 # 0000-GA-Barnetrygd-Beslutter
          - id: 93a26831-9866-4410-927b-74ff51a9107c # 0000-GA-Barnetrygd-Veileder
          - id: ee5e0b5e-454c-4612-b931-1fe363df7c2c # 0000-GA-Enslig-Forsorger-Saksbehandler
          - id: 01166863-22f1-4e16-9785-d7a05a22df74 # 0000-GA-Enslig-Forsorger-Beslutter
          - id: 19dcbfde-4cdb-4c64-a1ea-ac9802b03339 # 0000-GA-Enslig-Forsorger-Veileder
          - id: c62e908a-cf20-4ad0-b7b3-3ff6ca4bf38b # forvalterrolle 
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://tilbakekreving.ansatt.dev.nav.no/auth/openid/callback"
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: ida
          namespace: default
          cluster: prod-fss
    outbound:
      rules:
        - application: tilbakekreving-backend
  env:
    - name: ENV
      value: preprod
    - name: APP_VERSION
      value: {{ VERSION }}
    - name: TILBAKE_SCOPE
      value: api://dev-gcp.tilbake.tilbakekreving-backend/.default
  envFrom:
    - secret: tilbakekreving-frontend
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 200m

  redis:
    - instance: sessions
      access: readwrite
    - instance: lookup
      access: read
