apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tilbakekreving-frontend
  namespace: tilbake
  labels:
    team: tilbake
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://tilbakekreving.intern.nav.no
  vault:
    enabled: false
  azure:
    application:
      claims:
        groups:
          - id: 847e3d72-9dc1-41c3-80ff-f5d4acdd5d46 # 0000-GA-Barnetrygd
          - id: 7a271f87-39fb-468b-a9ee-6cf3c070f548 # 0000-GA-Barnetrygd-Beslutter
          - id: 199c2b39-e535-4ae8-ac59-8ccbee7991ae # 0000-GA-Barnetrygd-Veileder
          - id: e40090eb-c2fb-400e-b412-e9084019a73b # 0000-GA-Kontantstøtte
          - id: 54cd86b8-2e23-48b2-8852-b05b5827bb0f # 0000-GA-Kontantstøtte-Veileder
          - id: 6406aba2-b930-41d3-a85b-dd13731bc974 # 0000-GA-Enslig-Forsorger-Saksbehandler
          - id: 5fcc0e1d-a4c2-49f0-93dc-27c9fea41e54 # 0000-GA-Enslig-Forsorger-Beslutter
          - id: 31778fd8-3b71-4867-8db6-a81235fbe001 # 0000-GA-Enslig-Forsorger-Veileder
          - id: 3d718ae5-f25e-47a4-b4b3-084a97604c1d # forvalterrolle 
      enabled: true
      replyURLs:
        - "https://tilbakekreving.intern.nav.no/auth/openid/callback"
  webproxy: true
  accessPolicy:
    outbound:
      rules:
        - application: tilbakekreving-backend
  env:
    - name: ENV
      value: production
    - name: APP_VERSION
      value: {{ VERSION }}
    - name: TILBAKE_SCOPE
      value: api://prod-gcp.tilbake.tilbakekreving-backend/.default
    - name: TILBAKEKREVING_SVC_URL
      value: http://familie-tilbake/api
    - name: TILBAKEKREVING_BASE_DOMAIN
      value: tilbakekreving.intern.nav.no
  envFrom:
    - secret: tilbakekreving-frontend
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 200m

  redis:
    - instance: sessions
      access: readwrite
    - instance: lookup
      access: read
  valkey:
    - instance: sessions
      access: readwrite
    - instance: lookup
      access: read
