apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tilbakekreving-frontend
  namespace: tilbake
  labels:
    team: tilbake
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://tilbakekreving.intern.nav.no
  vault:
    enabled: false
  azure:
    application:
      claims:
        groups:
          - id: 847e3d72-9dc1-41c3-80ff-f5d4acdd5d46 # 0000-GA-Barnetrygd
          - id: 7a271f87-39fb-468b-a9ee-6cf3c070f548 # 0000-GA-Barnetrygd-Beslutter
          - id: 199c2b39-e535-4ae8-ac59-8ccbee7991ae # 0000-GA-Barnetrygd-Veileder
          - id: e40090eb-c2fb-400e-b412-e9084019a73b # 0000-GA-Kontantstøtte
          - id: 54cd86b8-2e23-48b2-8852-b05b5827bb0f # 0000-GA-Kontantstøtte-Veileder
          - id: 6406aba2-b930-41d3-a85b-dd13731bc974 # 0000-GA-Enslig-Forsorger-Saksbehandler
          - id: 5fcc0e1d-a4c2-49f0-93dc-27c9fea41e54 # 0000-GA-Enslig-Forsorger-Beslutter
          - id: 31778fd8-3b71-4867-8db6-a81235fbe001 # 0000-GA-Enslig-Forsorger-Veileder
          - id: 0f841c83-0d64-407c-80d5-4eb51dfaee1e # TS veileder
          - id: c1e9edec-0c10-4df2-8c74-324ab9922220 # TS saksbehandler
          - id: 224b5097-d0af-462c-8d8e-49c0e8a42661 # TS beslutter
          - id: dc8b0182-1449-445a-833c-1a4620b7c2be # 0000-GA-AAP_SAKSBEHANDLER_OPPFOLGING
          - id: 3a65f41a-b3f3-4b1c-830a-df20ff020980 # 0000-GA-AAP_SAKSBEHANDLER_NASJONAL
          - id: 5763b52f-f16a-483d-8f40-25be9de95c0a # 0000-GA-AAP_BESLUTTER
          - id: 3d718ae5-f25e-47a4-b4b3-084a97604c1d # forvalterrolle
      enabled: true
      replyURLs:
        - "https://tilbakekreving.intern.nav.no/auth/openid/callback"
    sidecar:
      enabled: true
  webproxy: true
  accessPolicy:
    outbound:
      rules:
        - application: tilbakekreving-backend
  env:
    - name: ENV
      value: production
    - name: APP_VERSION
      value: {{ VERSION }}
    - name: TILBAKE_SCOPE
      value: api://prod-gcp.tilbake.tilbakekreving-backend/.default
    - name: TILBAKEKREVING_BASE_DOMAIN
      value: tilbakekreving.intern.nav.no
  envFrom:
    - secret: tilbakekreving-frontend
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 200m

  valkey:
    - instance: sessions
      access: readwrite
