apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-tilbake-frontend-redis-exporter
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: oliver006/redis_exporter:v1.23.1
  port: 9121
  prometheus:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 100m 
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  liveness:
    path: /health
  accessPolicy:
    outbound:
      rules:
        - application: familie-tilbake-frontend-redis
  envFrom:
    - secret: familie-tilbake-frontend-redis
  env:
    - name: REDIS_ADDR
      value: familie-tilbake-frontend-redis:6379
    - name: REDIS_EXPORTER_LOG_FORMAT
      value: json