apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-tilbake-frontend
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://familietilbakekreving.intern.nav.no
  vault:
    enabled: false
  azure:
    application:
      claims:
        groups:
          - id: 847e3d72-9dc1-41c3-80ff-f5d4acdd5d46 # Barnetrygd - Saksbehandler
          - id: 7a271f87-39fb-468b-a9ee-6cf3c070f548 # Barnetrygd - Beslutter
          - id: 199c2b39-e535-4ae8-ac59-8ccbee7991ae # Barnetrygd - Veileder
          - id: e40090eb-c2fb-400e-b412-e9084019a73b # 0000-GA-Kontantstøtte
          - id: 54cd86b8-2e23-48b2-8852-b05b5827bb0f # 0000-GA-Kontantstøtte-Veileder
          - id: 31778fd8-3b71-4867-8db6-a81235fbe001 # Enslig Forsørger - Veileder
          - id: 6406aba2-b930-41d3-a85b-dd13731bc974 # Enslig Forsørger - Saksbehandler
          - id: 5fcc0e1d-a4c2-49f0-93dc-27c9fea41e54 # Enslig Forsørger - Beslutter
      enabled: true
      replyURLs:
        - "https://familietilbakekreving.intern.nav.no/auth/openid/callback"
  webproxy: true
  accessPolicy:
    outbound:
      rules:
        - application: familie-tilbake
        - application: familie-tilbake-frontend-redis
        - application: familie-historikk
  env:
    - name: ENV
      value: prod
    - name: APP_VERSION
      value: {{ VERSION }}
    - name: FAMILIE_TILBAKE_CLIENT_ID
      value: prod-gcp.teamfamilie.familie-tilbake
    - name: FAMILIE_HISTORIKK_CLIENT_ID
      value: prod-gcp.teamfamilie.familie-historikk
  envFrom:
    - secret: familie-tilbake-frontend
    - secret: familie-tilbake-frontend-redis
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 200m
