apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-tilbake-frontend
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://familie-tilbake-frontend.dev.intern.nav.no
  vault:
    enabled: false
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://familie-tilbake-frontend.dev.intern.nav.no/auth/openid/callback"
  webproxy: true
  accessPolicy:
    outbound:
      rules:
        - application: familie-tilbake-frontend-redis
      external: 
        - host: familie-tilbake.dev-fss-pub.nais.io
  env:
    - name: ENV
      value: preprod
    - name: APP_VERSION
      value: {{ VERSION }}
    - name: REDIS_HOST
      value: familie-tilbake-frontend-redis
    - name: FAMILIE_TILBAKE_SCOPE
      value: api://familie-tilbake/.default
  envFrom:
    - secret: familie-tilbake-frontend
    - secret: familie-tilbake-frontend-redis
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 200m
