export enum HendelseType {
    // Felles
    Annet = 'ANNET',
    Dødsfall = 'DØDSFALL',
    // Barnetrygd
    BorMedSøker = 'BOR_MED_SØKER',
    BosattIRiket = 'BOSATT_I_RIKET',
    LovligOpphold = 'LOVLIG_OPPHOLD',
    DeltBosted = 'DELT_BOSTED',
    BarnsAlder = 'BARNS_ALDER',
    MedlemskapBA = 'MEDLEMSKAP_BA',
    Utvidet = 'UTVIDET',
    Satser = 'SATSER',
    Småbarnstillegg = 'SMÅBARNSTILLEGG',
    // Felles Enslig forsørger
    Medlemskap = 'MEDLEMSKAP',
    OppholdINorge = 'OPPHOLD_I_NORGE',
    EnsligForsørger = 'ENSLIG_FORSØRGER',
    // Overgangsstønad
    Overgangsstønad = 'OVERGANGSSTØNAD',
    YrkesrettetAktivitet = 'YRKESRETTET_AKTIVITET',
    Stønadsperiode = 'STØNADSPERIODE',
    Inntekt = 'INNTEKT',
    Pensjonsytelser = 'PENSJONSYTELSER',
    // Barnetilsyn
    StønadTilBarnetilsyn = 'STØNAD_TIL_BARNETILSYN',
    // Skolepenger
    Skolepenger = 'SKOLEPENGER',
    // Kontantstøtte
    VilkårBarn = 'VILKÅR_BARN',
    VilkårSøker = 'VILKÅR_SØKER',
    BarnIFosterhjemEllerInstitusjon = 'BARN_I_FOSTERHJEM_ELLER_INSTITUSJON',
    KontantstøttensStørrelse = 'KONTANTSTØTTENS_STØRRELSE',
    Støtteperiode = 'STØTTEPERIODE',
    Utbetaling = 'UTBETALING',
    KontantstøtteForAdopterteBarn = 'KONTANTSTØTTE_FOR_ADOPTERTE_BARN',
    AnnetKS = 'ANNET_KS',
}

export const hendelsetyper: Record<HendelseType, string> = {
    // Felles
    [HendelseType.Annet]: 'Annet',
    [HendelseType.Dødsfall]: 'Dødsfall',
    // Barnetrygd
    [HendelseType.BorMedSøker]: 'Bor med søker',
    [HendelseType.BosattIRiket]: 'Bosatt i riket',
    [HendelseType.LovligOpphold]: 'Lovlig opphold',
    [HendelseType.DeltBosted]: 'Delt bosted',
    [HendelseType.BarnsAlder]: 'Barns alder',
    [HendelseType.MedlemskapBA]: 'Medlemskap',
    [HendelseType.Utvidet]: 'Utvidet',
    [HendelseType.Satser]: 'Satser',
    [HendelseType.Småbarnstillegg]: 'Småbarnstillegg',
    // Felles Enslig forsørger
    [HendelseType.Medlemskap]: '§15-2 Medlemskap',
    [HendelseType.OppholdINorge]: '§15-3 Opphold i Norge',
    [HendelseType.EnsligForsørger]: '§15-4 Enslig forsørger',
    // Overgangsstønad
    [HendelseType.Overgangsstønad]: '§15-5 Overgangsstønad',
    [HendelseType.YrkesrettetAktivitet]: '§15-6 Yrkesrettet aktivitet',
    [HendelseType.Stønadsperiode]: '§15-8 Stønadsperiode',
    [HendelseType.Inntekt]: '§15-9 Inntekt',
    [HendelseType.Pensjonsytelser]: '§15-13 Pensjonsytelser',
    // Barnetilsyn
    [HendelseType.StønadTilBarnetilsyn]: '§15-10 Stønad til barnetilsyn',
    // Skolepenger
    [HendelseType.Skolepenger]: '§15-11 Skolepenger',
    // Kontantstøtte
    [HendelseType.VilkårBarn]: '§2 Vilkår barn',
    [HendelseType.VilkårSøker]: '§3 Vilkår søker (støttemottaker)',
    [HendelseType.BarnIFosterhjemEllerInstitusjon]: '§6 Barn i fosterhjem eller institusjon',
    [HendelseType.KontantstøttensStørrelse]: '§7 Kontantstøttens størrelse',
    [HendelseType.Støtteperiode]: '§8 Støtteperiode',
    [HendelseType.Utbetaling]: '§9 Utbetaling',
    [HendelseType.KontantstøtteForAdopterteBarn]: '§10 Kontantstøtte for adopterte barn',
    [HendelseType.AnnetKS]: 'Annet',
};

export enum HendelseUndertype {
    // Felles
    AnnetFritekst = 'ANNET_FRITEKST',
    BrukerFlyttetFraNorge = 'BRUKER_FLYTTET_FRA_NORGE',
    BarnDød = 'BARN_DØD',
    BrukerDød = 'BRUKER_DØD',
    // Barnetrygd
    BrukerOgBarnFlyttetFraNorge = 'BRUKER_OG_BARN_FLYTTET_FRA_NORGE',
    BrukerOgBarnBorIkkeINorge = 'BRUKER_OG_BARN_BOR_IKKE_I_NORGE',
    BorIkkeMedBarn = 'BOR_IKKE_MED_BARN',
    BarnBorIkkeINorge = 'BARN_BOR_IKKE_I_NORGE',
    BrukerBorIkkeINorge = 'BRUKER_BOR_IKKE_I_NORGE',
    UtenOppholdstillatelse = 'UTEN_OPPHOLDSTILLATELSE',
    EnighetOmOpphørDeltBosted = 'ENIGHET_OM_OPPHØR_DELT_BOSTED',
    UenighetOmOpphørDeltBosted = 'UENIGHET_OM_OPPHØR_DELT_BOSTED',
    FlyttetSammen = 'FLYTTET_SAMMEN',
    BarnOver18År = 'BARN_OVER_18_ÅR',
    BarnOver6År = 'BARN_OVER_6_ÅR',
    UtenlandsIkkeMedlem = 'UTENLANDS_IKKE_MEDLEM',
    MedlemskapOpphørt = 'MEDLEMSKAP_OPPHØRT',
    AnnenForelderIkkeMedlem = 'ANNEN_FORELDER_IKKE_MEDLEM',
    AnnenForelderOpphørtMedlemskap = 'ANNEN_FORELDER_OPPHØRT_MEDLEMSKAP',
    FlereUtenlandsopphold = 'FLERE_UTENLANDSOPPHOLD',
    BosattIkkeMedlem = 'BOSATT_IKKE_MEDLEM',
    Gift = 'GIFT',
    NyttBarn = 'NYTT_BARN',
    Samboer12Måneder = 'SAMBOER_12_MÅNEDER',
    FlyttetSammenAnnenForelder = 'FLYTTET_SAMMEN_ANNEN_FORELDER',
    FlyttetSammenEktefelle = 'FLYTTET_SAMMEN_EKTEFELLE',
    FlyttetSammenSamboer = 'FLYTTET_SAMMEN_SAMBOER',
    GiftIkkeEgenHusholdning = 'GIFT_IKKE_EGEN_HUSHOLDNING',
    SamboerIkkeEgenHusholdning = 'SAMBOER_IKKE_EGEN_HUSHOLDNING',
    EktefelleAvsluttetSoning = 'EKTEFELLE_AVSLUTTET_SONING',
    SamboerAvsluttetSoning = 'SAMBOER_AVSLUTTET_SONING',
    EktefelleInstitusjon = 'EKTEFELLE_INSTITUSJON',
    SamboerIntitusjon = 'SAMBOER_INSTITUSJON',
    Satsendring = 'SATSENDRING',
    Småbarnstillegg3År = 'SMÅBARNSTILLEGG_3_ÅR',
    SmåbarnstilleggOvergangsstønad = 'SMÅBARNSTILLEGG_OVERGANGSSTØNAD',
    // Felles Enslig forsørger
    MedlemSiste5År = 'MEDLEM_SISTE_5_ÅR',
    LovligOpphold = 'LOVLIG_OPPHOLD',
    BrukerIkkeOppholdINorge = 'BRUKER_IKKE_OPPHOLD_I_NORGE',
    BarnIkkeOppholdINorge = 'BARN_IKKE_OPPHOLD_I_NORGE',
    OppholdUtland6UkerEllerMer = 'OPPHOLD_UTLAND_6_UKER_ELLER_MER',
    Ugift = 'UGIFT',
    SeparertSkilt = 'SEPARERT_SKILT',
    Samboer = 'SAMBOER',
    NyttBarnSammePartner = 'NYTT_BARN_SAMME_PARTNER',
    EndretSamværsordning = 'ENDRET_SAMVÆRSORDNING',
    BarnFlyttet = 'BARN_FLYTTET',
    NæreBoforhold = 'NÆRE_BOFORHOLD',
    ForeldreLeverSammen = 'FORELDRE_LEVER_SAMMEN',
    // Overgangsstønad
    Barn8År = 'BARN_8_ÅR',
    Arbeid = 'ARBEID',
    ReelArbeidssøker = 'REELL_ARBEIDSSØKER',
    Utdanning = 'UTDANNING',
    EtablererEgenVirksomhet = 'ETABLERER_EGEN_VIRKSOMHET',
    Hovedperiode3År = 'HOVEDPERIODE_3_ÅR',
    UtvidelseUtdanning = 'UTVIDELSE_UTDANNING',
    UtvidelseSærligTilsynskrevendeBarn = 'UTVIDELSE_SÆRLIG_TILSYNSKREVENDE_BARN',
    UtvidelseForbigåendeSykdom = 'UTVIDELSE_FORBIGÅENDE_SYKDOM',
    PåventeAvSkolestartStartetIkke = 'PÅVENTE_AV_SKOLESTART_STARTET_IKKE',
    PåventeSkolestartStartetTidligere = 'PÅVENTE_SKOLESTART_STARTET_TIDLIGERE',
    PåventeArbeidstilbudStartetIkke = 'PÅVENTE_ARBEIDSTILBUD_STARTET_IKKE',
    PåventeArbeidstilbudStartetTidligere = 'PÅVENTE_ARBEIDSTILBUD_STARTET_TIDLIGERE',
    PåventeBarnetilsynIkkeHaTilsyn = 'PÅVENTE_BARNETILSYN_IKKE_HA_TILSYN',
    PåventeBarnetilsynStartetTidligere = 'PÅVENTE_BARNETILSYN_STARTET_TIDLIGERE',
    Arbeidssøker = 'ARBEIDSSØKER',
    ArbeidsinntektFåttInntekt = 'ARBEIDSINNTEKT_FÅTT_INNTEKT',
    ArbeidsinntektEndreInntekt = 'ARBEIDSINNTEKT_ENDRET_INNTEKT',
    AndreFolketrygdytelser = 'ANDRE_FOLKETRYGDYTELSER',
    SelvstendigNæringsdrivendeFåttInntekt = 'SELVSTENDIG_NÆRINGSDRIVENDE_FÅTT_INNTEKT',
    SelvstendigNæringsdrivendeEndretInntekt = 'SELVSTENDIG_NÆRINGSDRIVENDE_ENDRET_INNTEKT',
    Uføretrygd = 'UFØRETRYGD',
    GjenlevendeEktefelle = 'GJENLEVENDE_EKTEFELLE',
    BarnFylt1År = 'BARN_FYLT_1_ÅR',
    // Barnetilsyn
    IkkeArbeid = 'IKKE_ARBEID',
    EgenVirksomhet = 'EGEN_VIRKSOMHET',
    TilsynsutgifterOpphørt = 'TILSYNSUTGIFTER_OPPHØRT',
    TilsynsutgifterEndret = 'TILSYNSUTGIFTER_ENDRET',
    ForbigåendeSykdom = 'FORBIGÅENDE_SYKDOM',
    Etter4SkoleårUtgifteneOpphørt = 'ETTER_4_SKOLEÅR_UTGIFTENE_OPPHØRT',
    Etter4SkoleårEndretArbeidstid = 'ETTER_4_SKOLEÅR_ENDRET_ARBEIDSTID',
    InntektOver6G = 'INNTEKT_OVER_6G',
    KontantStøtte = 'KONTANTSTØTTE',
    ØktKontantstøtte = 'ØKT_KONTANTSTØTTE',
    // Skolepenger
    IkkeRettTilOvergangsstønad = 'IKKE_RETT_TIL_OVERGANGSSTØNAD',
    SluttetIUtdanning = 'SLUTTET_I_UTDANNING',
    // Kontanstøtte
    FulltidBarnehageplass = 'FULLTID_BARNEHAGEPLASS',
    Over2År = 'OVER_2_ÅR',
    BarnIkkeBosatt = 'BARN_IKKE_BOSATT',
    BarnIkkeOppholdstillatelse = 'BARN_IKKE_OPPHOLDSTILLATELSE',
    BarnFlyttetFraNorge = 'BARN_FLYTTET_FRA_NORGE',
    BarnOver2År = 'BARN_OVER_2_ÅR',
    DenAndreForelderenIkkeMedlemFolketrygden = 'DEN_ANDRE_FORELDEREN_IKKE_MEDLEM_FOLKETRYGDEN',
    DenAndreForelderenIkkeMedlemFolketrygdenEllerEØS = 'DEN_ANDRE_FORELDEREN_IKKE_MEDLEM_FOLKETRYGDEN_ELLER_EØS',
    SøkerIkkeMedlemFolketrygden = 'SØKER_IKKE_MEDLEM_FOLKETRYGDEN',
    SøkerIkkeMedlemFolketrygdenEllerEØS = 'SØKER_IKKE_MEDLEM_FOLKETRYGDEN_ELLER_EØS',
    BeggeForeldreneIkkeMedlemFolketrygden = 'BEGGE_FORELDRENE_IKKE_MEDLEM_FOLKETRYGDEN',
    BeggeForeldreneIkkeMedlemFolketrygdenEllerEØS = 'BEGGE_FORELDRENE_IKKE_MEDLEM_FOLKETRYGDEN_ELLER_EØS',
    BarnBorIkkeHosSøker = 'BARN_BOR_IKKE_HOS_SØKER',
    UtenlandsoppholdOver3Måneder = 'UTENLANDSOPPHOLD_OVER_3_MÅNEDER',
    SøkerFlyttetFraNorge = 'SØKER_FLYTTET_FRA_NORGE',
    SøkerIkkeBosatt = 'SØKER_IKKE_BOSATT',
    SøkerIkkeOppholdstillatelse = 'SØKER_IKKE_OPPHOLDSTILLATELSE',
    SøkerIkkeOppholdstillatelseIMerEnn12Måneder = 'SØKER_IKKE_OPPHOLDSTILLATELSE_I_MER_ENN_12_MÅNEDER',
    BarnIFosterhjem = 'BARN_I_FOSTERHJEM',
    BarnIInstitusjon = 'BARN_I_INSTITUSJON',
    FulltidsplassBarnehage = 'FULLTIDSPLASS_BARNEHAGE',
    DeltidsplassBarnehageplass = 'DELTIDSPLASS_BARNEHAGEPLASS',
    ØktTimeantallIBarnehage = 'ØKT_TIMEANTALL_I_BARNEHAGE',
    Barn2År = 'BARN_2_ÅR',
    DeltBostedAvtaleOpphørt = 'DELT_BOSTED_AVTALE_OPPHØRT',
    Dobbeltutbetaling = 'DOBBELUTBETALING',
    MerEnn11Måneder = 'MER_ENN_11_MÅNEDER',
    BarnStartetPåSkolen = 'BARN_STARTET_PÅ_SKOLEN',
}

export const hendelseundertyper: Record<HendelseUndertype, string> = {
    // Felles
    [HendelseUndertype.AnnetFritekst]: 'Annet fritekst',
    [HendelseUndertype.BrukerFlyttetFraNorge]: 'Bruker flyttet fra Norge',
    [HendelseUndertype.BarnFlyttetFraNorge]: 'Barn flyttet fra Norge',
    [HendelseUndertype.BarnDød]: 'Barnet død',
    [HendelseUndertype.BrukerDød]: 'Bruker død',
    // Barnetrygd
    [HendelseUndertype.BrukerOgBarnFlyttetFraNorge]: 'Bruker og barn flyttet fra Norge',
    [HendelseUndertype.BrukerOgBarnBorIkkeINorge]: 'Bruker og barn bor ikke i Norge',
    [HendelseUndertype.BorIkkeMedBarn]: 'Bor ikke med barn - ikke fast omsorg',
    [HendelseUndertype.BarnBorIkkeINorge]: 'Barn bor ikke i Norge',
    [HendelseUndertype.BrukerBorIkkeINorge]: 'Bruker bor ikke i Norge',
    [HendelseUndertype.UtenOppholdstillatelse]: 'Bruker uten oppholdstillatelse',
    [HendelseUndertype.EnighetOmOpphørDeltBosted]: 'Enighet om opphør av avtale om delt bosted',
    [HendelseUndertype.UenighetOmOpphørDeltBosted]: 'Uenighet om opphør av avtale om delt bosted',
    [HendelseUndertype.FlyttetSammen]: 'Flyttet sammen',
    [HendelseUndertype.BarnOver18År]: 'Barn over 18 år',
    [HendelseUndertype.BarnOver6År]: 'Barn over 6 år',
    [HendelseUndertype.UtenlandsIkkeMedlem]: 'Utenlands ikke medlem',
    [HendelseUndertype.MedlemskapOpphørt]: 'Medlemskap opphørt',
    [HendelseUndertype.AnnenForelderIkkeMedlem]: 'Den andre forelderen ikke medlem',
    [HendelseUndertype.AnnenForelderOpphørtMedlemskap]: 'Den andre forelderen opphørt medlemskap',
    [HendelseUndertype.FlereUtenlandsopphold]: 'Flere utenlandsopphold',
    [HendelseUndertype.BosattIkkeMedlem]: 'Bosatt ikke medlem',
    [HendelseUndertype.Gift]: 'Gift',
    [HendelseUndertype.NyttBarn]: 'Nytt barn',
    [HendelseUndertype.Samboer12Måneder]: 'Samboer mer enn 12 måneder',
    [HendelseUndertype.FlyttetSammenAnnenForelder]: 'Flyttet sammen med annen forelder',
    [HendelseUndertype.FlyttetSammenEktefelle]: 'Flyttet sammen med ektefelle',
    [HendelseUndertype.FlyttetSammenSamboer]: 'Flyttet sammen med samboer',
    [HendelseUndertype.GiftIkkeEgenHusholdning]: 'Gift ikke egen husholdning',
    [HendelseUndertype.SamboerIkkeEgenHusholdning]: 'Samboer ikke egen husholdning',
    [HendelseUndertype.EktefelleAvsluttetSoning]: 'Ektefelle avsluttet soning',
    [HendelseUndertype.SamboerAvsluttetSoning]: 'Samboer avsluttet soning',
    [HendelseUndertype.EktefelleInstitusjon]: 'Ektefelle institusjon',
    [HendelseUndertype.SamboerIntitusjon]: 'Samboer institusjon',
    [HendelseUndertype.Satsendring]: 'Satsendring',
    [HendelseUndertype.Småbarnstillegg3År]: 'Småbarnstillegg 3 år',
    [HendelseUndertype.SmåbarnstilleggOvergangsstønad]: 'Småbarnstillegg overgangsstønad',
    // Felles Enslig forsørger
    [HendelseUndertype.MedlemSiste5År]: 'Medlem siste 5 år',
    [HendelseUndertype.LovligOpphold]: 'Lovlig opphold',
    [HendelseUndertype.BrukerIkkeOppholdINorge]: 'Bruker ikke opphold i Norge',
    [HendelseUndertype.BarnIkkeOppholdINorge]: 'Barn ikke opphold i Norge',
    [HendelseUndertype.OppholdUtland6UkerEllerMer]: 'Opphold utland 6 uker eller mer',
    [HendelseUndertype.Ugift]: 'Ugift (3. ledd)',
    [HendelseUndertype.SeparertSkilt]: 'Separert/ skilt (3. ledd)',
    [HendelseUndertype.Samboer]: 'Samboer (3. ledd)',
    [HendelseUndertype.NyttBarnSammePartner]: 'Nytt barn samme partner (3. ledd)',
    [HendelseUndertype.EndretSamværsordning]: 'Endret samværsordning (4.ledd)',
    [HendelseUndertype.BarnFlyttet]: 'Barn flyttet (4.ledd)',
    [HendelseUndertype.NæreBoforhold]: 'Nære boforhold (4.ledd)',
    [HendelseUndertype.ForeldreLeverSammen]: 'Foreldre lever sammen (4.ledd)',
    // Overgangsstønad
    [HendelseUndertype.Barn8År]: 'Barn 8 år (2. ledd)',
    [HendelseUndertype.Arbeid]: 'Arbeid',
    [HendelseUndertype.ReelArbeidssøker]: 'Reell arbeidssøker',
    [HendelseUndertype.Utdanning]: 'Utdanning',
    [HendelseUndertype.EtablererEgenVirksomhet]: 'Etablerer egen virksomhet',
    [HendelseUndertype.Hovedperiode3År]: 'Hovedperiode 3 år (1.ledd)',
    [HendelseUndertype.UtvidelseUtdanning]: 'Utvidelse utdanning (2. ledd)',
    [HendelseUndertype.UtvidelseSærligTilsynskrevendeBarn]:
        'Utvidelse særlig tilsynskrevende barn (3. ledd)',
    [HendelseUndertype.UtvidelseForbigåendeSykdom]: 'Utvidelse, forbigående sykdom (4. ledd)',
    [HendelseUndertype.PåventeAvSkolestartStartetIkke]:
        'Påvente av skolestart, startet ikke (5.ledd)',
    [HendelseUndertype.PåventeSkolestartStartetTidligere]:
        'Påvente skolestart, startet tidligere (5.ledd)',
    [HendelseUndertype.PåventeArbeidstilbudStartetIkke]:
        'Påvente arbeidstilbud, startet ikke (5.ledd)',
    [HendelseUndertype.PåventeArbeidstilbudStartetTidligere]:
        'Påvente arbeidstilbud, startet tidligere (5.ledd)',
    [HendelseUndertype.PåventeBarnetilsynIkkeHaTilsyn]:
        'Påvente barnetilsyn, ikke ha tilsyn (5.ledd)',
    [HendelseUndertype.PåventeBarnetilsynStartetTidligere]:
        'Påvente barnetilsyn, startet tidligere (5.ledd)',
    [HendelseUndertype.Arbeidssøker]: 'Reell arbeidssøker (5.ledd)',
    [HendelseUndertype.ArbeidsinntektFåttInntekt]: 'Arbeidsinntekt, fått inntekt',
    [HendelseUndertype.ArbeidsinntektEndreInntekt]: 'Arbeidsinntekt, endret inntekt',
    [HendelseUndertype.AndreFolketrygdytelser]: 'Andre folketrygdytelser',
    [HendelseUndertype.SelvstendigNæringsdrivendeFåttInntekt]:
        'Selvstendig næringsdrivende, fått inntekt',
    [HendelseUndertype.SelvstendigNæringsdrivendeEndretInntekt]:
        'Selvstendig næringsdrivende, endret inntekt',
    [HendelseUndertype.Uføretrygd]: 'Uføretrygd',
    [HendelseUndertype.GjenlevendeEktefelle]: 'Gjenlevende ektefelle',
    [HendelseUndertype.BarnFylt1År]: 'Barn fylt 1 år',
    // Barnetilsyn
    [HendelseUndertype.IkkeArbeid]: 'Arbeid (1. ledd)',
    [HendelseUndertype.EgenVirksomhet]: 'Egen virksomhet (1. ledd)',
    [HendelseUndertype.TilsynsutgifterOpphørt]: 'Tilsynsutgifter opphørt',
    [HendelseUndertype.TilsynsutgifterEndret]: 'Tilsynsutgifter endret',
    [HendelseUndertype.ForbigåendeSykdom]: 'Forbigående sykdom (2. ledd)',
    [HendelseUndertype.Etter4SkoleårUtgifteneOpphørt]:
        'Tilsynsutgifter etter 4. skoleår, utgiftene opphørt (2. ledd)',
    [HendelseUndertype.Etter4SkoleårEndretArbeidstid]:
        'Tilsynsutgifter etter 4. skoleår, endret arbeidstid (2. ledd)',
    [HendelseUndertype.InntektOver6G]: 'Inntekt over 6G (3. ledd)',
    [HendelseUndertype.KontantStøtte]: 'Kontantstøtte',
    [HendelseUndertype.ØktKontantstøtte]: 'Økt kontantstøtte',
    // Skolepenger
    [HendelseUndertype.IkkeRettTilOvergangsstønad]: 'Ikke rett til overgangsstønad (5. ledd)',
    [HendelseUndertype.SluttetIUtdanning]: 'Sluttet i utdanning',
    // Kontantstøtte
    [HendelseUndertype.FulltidBarnehageplass]: 'Fulltid barnehageplass',
    [HendelseUndertype.Over2År]: 'Barn over 2 år',
    [HendelseUndertype.BarnIkkeBosatt]: 'Barn ikke bosatt',
    [HendelseUndertype.BarnIkkeOppholdstillatelse]: 'Barn ikke oppholdstillatelse',
    [HendelseUndertype.BarnOver2År]: 'Barn over 2 år',
    [HendelseUndertype.DenAndreForelderenIkkeMedlemFolketrygden]:
        'Den andre forelderen ikke medlem folketrygden',
    [HendelseUndertype.DenAndreForelderenIkkeMedlemFolketrygdenEllerEØS]:
        'Den andre forelderen ikke medlem folketrygden eller EØS',
    [HendelseUndertype.SøkerIkkeMedlemFolketrygden]: 'Søker ikke medlem folketrygden',
    [HendelseUndertype.SøkerIkkeMedlemFolketrygdenEllerEØS]:
        'Søker ikke medlem folketrygden eller EØS',
    [HendelseUndertype.BeggeForeldreneIkkeMedlemFolketrygden]:
        'Begge foreldrene ikke medlem folketrygden',
    [HendelseUndertype.BeggeForeldreneIkkeMedlemFolketrygdenEllerEØS]:
        'Begge foreldrene ikke medlem folketrygden eller EØS',
    [HendelseUndertype.BarnBorIkkeHosSøker]: 'Barn bor ikke hos søker',
    [HendelseUndertype.UtenlandsoppholdOver3Måneder]: 'Utenlandsopphold over 3 måneder',
    [HendelseUndertype.SøkerFlyttetFraNorge]: 'Søker flyttet fra Norge',
    [HendelseUndertype.SøkerIkkeBosatt]: 'Søker ikke bosatt',
    [HendelseUndertype.SøkerIkkeOppholdstillatelse]: 'Søker ikke oppholdstillatelse',
    [HendelseUndertype.SøkerIkkeOppholdstillatelseIMerEnn12Måneder]:
        'Søker ikke oppholdstillatelse i mer enn 12 måneder',
    [HendelseUndertype.BarnIFosterhjem]: 'Barn i fosterhjem',
    [HendelseUndertype.BarnIInstitusjon]: 'Barn i institusjon',
    [HendelseUndertype.FulltidsplassBarnehage]: 'Fulltidsplass barnehage',
    [HendelseUndertype.DeltidsplassBarnehageplass]: 'Deltidsplass barnehageplass',
    [HendelseUndertype.ØktTimeantallIBarnehage]: 'Økt timeantall i barnehage',
    [HendelseUndertype.Barn2År]: 'Barn 2 år',
    [HendelseUndertype.DeltBostedAvtaleOpphørt]: 'Delt bosted, avtale opphørt',
    [HendelseUndertype.Dobbeltutbetaling]: 'Dobbelutbetaling',
    [HendelseUndertype.MerEnn11Måneder]: 'Mer enn 11 måneder',
    [HendelseUndertype.BarnStartetPåSkolen]: 'Barn startet på skolen',
};

const undertyper = {
    // Felles
    ANNET: [HendelseUndertype.AnnetFritekst],
    DØDSFALL: [HendelseUndertype.BarnDød, HendelseUndertype.BrukerDød],
    // Barnetrygd
    BOR_MED_SØKER: [HendelseUndertype.BorIkkeMedBarn],
    BOSATT_I_RIKET: [
        HendelseUndertype.BarnFlyttetFraNorge,
        HendelseUndertype.BrukerFlyttetFraNorge,
        HendelseUndertype.BrukerOgBarnFlyttetFraNorge,
        HendelseUndertype.BarnBorIkkeINorge,
        HendelseUndertype.BrukerBorIkkeINorge,
        HendelseUndertype.BrukerOgBarnBorIkkeINorge,
    ],
    LOVLIG_OPPHOLD: [HendelseUndertype.UtenOppholdstillatelse],
    DELT_BOSTED: [
        HendelseUndertype.EnighetOmOpphørDeltBosted,
        HendelseUndertype.UenighetOmOpphørDeltBosted,
        HendelseUndertype.FlyttetSammen,
    ],
    BARNS_ALDER: [HendelseUndertype.BarnOver18År, HendelseUndertype.BarnOver6År],
    MEDLEMSKAP_BA: [
        HendelseUndertype.UtenlandsIkkeMedlem,
        HendelseUndertype.MedlemskapOpphørt,
        HendelseUndertype.AnnenForelderIkkeMedlem,
        HendelseUndertype.AnnenForelderOpphørtMedlemskap,
        HendelseUndertype.FlereUtenlandsopphold,
        HendelseUndertype.BosattIkkeMedlem,
    ],
    UTVIDET: [
        HendelseUndertype.Gift,
        HendelseUndertype.NyttBarn,
        HendelseUndertype.Samboer12Måneder,
        HendelseUndertype.FlyttetSammenAnnenForelder,
        HendelseUndertype.FlyttetSammenEktefelle,
        HendelseUndertype.FlyttetSammenSamboer,
        HendelseUndertype.GiftIkkeEgenHusholdning,
        HendelseUndertype.SamboerIkkeEgenHusholdning,
        HendelseUndertype.EktefelleAvsluttetSoning,
        HendelseUndertype.SamboerAvsluttetSoning,
        HendelseUndertype.EktefelleInstitusjon,
        HendelseUndertype.SamboerIntitusjon,
    ],
    SATSER: [HendelseUndertype.Satsendring],
    SMÅBARNSTILLEGG: [
        HendelseUndertype.Småbarnstillegg3År,
        HendelseUndertype.SmåbarnstilleggOvergangsstønad,
    ],
    // Felles Enslig forsørger
    MEDLEMSKAP: [HendelseUndertype.MedlemSiste5År, HendelseUndertype.LovligOpphold],
    OPPHOLD_I_NORGE: [
        HendelseUndertype.BrukerIkkeOppholdINorge,
        HendelseUndertype.BarnIkkeOppholdINorge,
        HendelseUndertype.BrukerFlyttetFraNorge,
        HendelseUndertype.BarnFlyttetFraNorge,
        HendelseUndertype.OppholdUtland6UkerEllerMer,
    ],
    ENSLIG_FORSØRGER: [
        HendelseUndertype.Ugift,
        HendelseUndertype.SeparertSkilt,
        HendelseUndertype.Samboer,
        HendelseUndertype.NyttBarnSammePartner,
        HendelseUndertype.EndretSamværsordning,
        HendelseUndertype.BarnFlyttet,
        HendelseUndertype.NæreBoforhold,
        HendelseUndertype.ForeldreLeverSammen,
    ],
    // Overgangsstønad
    OVERGANGSSTØNAD: [HendelseUndertype.Barn8År],
    YRKESRETTET_AKTIVITET: [
        HendelseUndertype.Arbeid,
        HendelseUndertype.ReelArbeidssøker,
        HendelseUndertype.Utdanning,
        HendelseUndertype.EtablererEgenVirksomhet,
        HendelseUndertype.BarnFylt1År,
    ],
    STØNADSPERIODE: [
        HendelseUndertype.Hovedperiode3År,
        HendelseUndertype.UtvidelseUtdanning,
        HendelseUndertype.UtvidelseSærligTilsynskrevendeBarn,
        HendelseUndertype.UtvidelseForbigåendeSykdom,
        HendelseUndertype.PåventeAvSkolestartStartetIkke,
        HendelseUndertype.PåventeSkolestartStartetTidligere,
        HendelseUndertype.PåventeArbeidstilbudStartetIkke,
        HendelseUndertype.PåventeArbeidstilbudStartetTidligere,
        HendelseUndertype.PåventeBarnetilsynIkkeHaTilsyn,
        HendelseUndertype.PåventeBarnetilsynStartetTidligere,
        HendelseUndertype.Arbeidssøker,
    ],
    INNTEKT: [
        HendelseUndertype.ArbeidsinntektFåttInntekt,
        HendelseUndertype.ArbeidsinntektEndreInntekt,
        HendelseUndertype.AndreFolketrygdytelser,
        HendelseUndertype.SelvstendigNæringsdrivendeFåttInntekt,
        HendelseUndertype.SelvstendigNæringsdrivendeEndretInntekt,
    ],
    PENSJONSYTELSER: [HendelseUndertype.Uføretrygd, HendelseUndertype.GjenlevendeEktefelle],
    // Barnetilsyn
    STØNAD_TIL_BARNETILSYN: [
        HendelseUndertype.IkkeArbeid,
        HendelseUndertype.EgenVirksomhet,
        HendelseUndertype.TilsynsutgifterOpphørt,
        HendelseUndertype.TilsynsutgifterEndret,
        HendelseUndertype.ForbigåendeSykdom,
        HendelseUndertype.Etter4SkoleårUtgifteneOpphørt,
        HendelseUndertype.Etter4SkoleårEndretArbeidstid,
        HendelseUndertype.InntektOver6G,
        HendelseUndertype.KontantStøtte,
        HendelseUndertype.ØktKontantstøtte,
    ],
    // Skolepenger
    SKOLEPENGER: [
        HendelseUndertype.IkkeRettTilOvergangsstønad,
        HendelseUndertype.SluttetIUtdanning,
    ],
    VILKÅR_BARN: [
        HendelseUndertype.FulltidsplassBarnehage,
        HendelseUndertype.DeltidsplassBarnehageplass,
        HendelseUndertype.BarnIkkeBosatt,
        HendelseUndertype.BarnIkkeOppholdstillatelse,
        HendelseUndertype.BarnFlyttetFraNorge,
        HendelseUndertype.BarnOver2År,
    ],
    VILKÅR_SØKER: [
        HendelseUndertype.DenAndreForelderenIkkeMedlemFolketrygden,
        HendelseUndertype.DenAndreForelderenIkkeMedlemFolketrygdenEllerEØS,
        HendelseUndertype.SøkerIkkeMedlemFolketrygden,
        HendelseUndertype.SøkerIkkeMedlemFolketrygdenEllerEØS,
        HendelseUndertype.BeggeForeldreneIkkeMedlemFolketrygden,
        HendelseUndertype.BeggeForeldreneIkkeMedlemFolketrygdenEllerEØS,
        HendelseUndertype.BarnBorIkkeHosSøker,
        HendelseUndertype.UtenlandsoppholdOver3Måneder,
        HendelseUndertype.SøkerFlyttetFraNorge,
        HendelseUndertype.SøkerIkkeBosatt,
        HendelseUndertype.SøkerIkkeOppholdstillatelse,
        HendelseUndertype.SøkerIkkeOppholdstillatelseIMerEnn12Måneder,
    ],
    BARN_I_FOSTERHJEM_ELLER_INSTITUSJON: [
        HendelseUndertype.BarnIFosterhjem,
        HendelseUndertype.BarnIInstitusjon,
    ],
    KONTANTSTØTTENS_STØRRELSE: [
        HendelseUndertype.FulltidsplassBarnehage,
        HendelseUndertype.DeltidsplassBarnehageplass,
        HendelseUndertype.ØktTimeantallIBarnehage,
        HendelseUndertype.Satsendring,
    ],
    STØTTEPERIODE: [HendelseUndertype.Barn2År],
    UTBETALING: [HendelseUndertype.DeltBostedAvtaleOpphørt, HendelseUndertype.Dobbeltutbetaling],
    KONTANTSTØTTE_FOR_ADOPTERTE_BARN: [
        HendelseUndertype.MerEnn11Måneder,
        HendelseUndertype.BarnStartetPåSkolen,
    ],
    ANNET_KS: [
        HendelseUndertype.AnnetFritekst,
        HendelseUndertype.BarnDød,
        HendelseUndertype.BrukerDød,
    ],
};

export const hentHendelseUndertyper = (
    hendelseType: HendelseType | undefined
): HendelseUndertype[] => {
    return hendelseType ? undertyper[hendelseType] : [];
};
