// This file is auto-generated by @hey-api/openapi-ts

import type { BehandlingFaktaData } from '../types.gen';

import { queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { behandlingFakta, type Options } from '../sdk.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: readonly string[];
    },
];

const createQueryKey = <TOptions extends Options>(
    id: string,
    options?: TOptions,
    infinite?: boolean,
    tags?: readonly string[]
): [QueryKey<TOptions>[0]] => {
    const params: QueryKey<TOptions>[0] = {
        _id: id,
        baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL,
    } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const behandlingFaktaQueryKey = (options: Options<BehandlingFaktaData>) =>
    createQueryKey('behandlingFakta', options);

export const behandlingFaktaOptions = (options: Options<BehandlingFaktaData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await behandlingFakta({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: behandlingFaktaQueryKey(options),
    });
};
