// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import {
    behandlingFakta,
    behandlingOppdaterFakta,
    type Options,
    vedtaksbrevLagSvgVedtaksbrev,
} from '../sdk.gen';
import type {
    BehandlingFaktaData,
    BehandlingFaktaError,
    BehandlingFaktaResponse,
    BehandlingOppdaterFaktaData,
    BehandlingOppdaterFaktaError,
    BehandlingOppdaterFaktaResponse,
    VedtaksbrevLagSvgVedtaksbrevData,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    },
];

const createQueryKey = <TOptions extends Options>(
    id: string,
    options?: TOptions,
    infinite?: boolean,
    tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
    const params: QueryKey<TOptions>[0] = {
        _id: id,
        baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL,
    } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const behandlingFaktaQueryKey = (options: Options<BehandlingFaktaData>) =>
    createQueryKey('behandlingFakta', options);

export const behandlingFaktaOptions = (options: Options<BehandlingFaktaData>) =>
    queryOptions<
        BehandlingFaktaResponse,
        AxiosError<BehandlingFaktaError>,
        BehandlingFaktaResponse,
        ReturnType<typeof behandlingFaktaQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await behandlingFakta({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: behandlingFaktaQueryKey(options),
    });

export const behandlingOppdaterFaktaMutation = (
    options?: Partial<Options<BehandlingOppdaterFaktaData>>
): UseMutationOptions<
    BehandlingOppdaterFaktaResponse,
    AxiosError<BehandlingOppdaterFaktaError>,
    Options<BehandlingOppdaterFaktaData>
> => {
    const mutationOptions: UseMutationOptions<
        BehandlingOppdaterFaktaResponse,
        AxiosError<BehandlingOppdaterFaktaError>,
        Options<BehandlingOppdaterFaktaData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await behandlingOppdaterFakta({
                ...options,
                ...fnOptions,
                throwOnError: true,
            });
            return data;
        },
    };
    return mutationOptions;
};

export const vedtaksbrevLagSvgVedtaksbrevMutation = (
    options?: Partial<Options<VedtaksbrevLagSvgVedtaksbrevData>>
): UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<VedtaksbrevLagSvgVedtaksbrevData>
> => {
    const mutationOptions: UseMutationOptions<
        unknown,
        AxiosError<DefaultError>,
        Options<VedtaksbrevLagSvgVedtaksbrevData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await vedtaksbrevLagSvgVedtaksbrev({
                ...options,
                ...fnOptions,
                throwOnError: true,
            });
            return data;
        },
    };
    return mutationOptions;
};
