// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { fakta, oppdaterFakta, type Options } from '../sdk.gen';
import type {
    FaktaData,
    FaktaError,
    FaktaResponse,
    OppdaterFaktaData,
    OppdaterFaktaError,
    OppdaterFaktaResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    },
];

const createQueryKey = <TOptions extends Options>(
    id: string,
    options?: TOptions,
    infinite?: boolean,
    tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
    const params: QueryKey<TOptions>[0] = {
        _id: id,
        baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL,
    } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const faktaQueryKey = (options: Options<FaktaData>) => createQueryKey('fakta', options);

export const faktaOptions = (options: Options<FaktaData>) =>
    queryOptions<
        FaktaResponse,
        AxiosError<FaktaError>,
        FaktaResponse,
        ReturnType<typeof faktaQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await fakta({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: faktaQueryKey(options),
    });

export const oppdaterFaktaMutation = (
    options?: Partial<Options<OppdaterFaktaData>>
): UseMutationOptions<
    OppdaterFaktaResponse,
    AxiosError<OppdaterFaktaError>,
    Options<OppdaterFaktaData>
> => {
    const mutationOptions: UseMutationOptions<
        OppdaterFaktaResponse,
        AxiosError<OppdaterFaktaError>,
        Options<OppdaterFaktaData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await oppdaterFakta({
                ...options,
                ...fnOptions,
                throwOnError: true,
            });
            return data;
        },
    };
    return mutationOptions;
};
