// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://raw.githubusercontent.com' | (string & {});
};

export type RettsligGrunnlag = {
    bestemmelse: BestemmelseEllerGrunnlag;
    grunnlag: BestemmelseEllerGrunnlag;
};

export type BestemmelseEllerGrunnlag = {
    nøkkel: string;
    beskrivelse: string;
};

export type Periode = {
    id: string;
    fom: string;
    tom: string;
    feilutbetaltBeløp: number;
    splittbarePerioder: {
        id: string;
        fom: string;
        tom: string;
        feilutbetaltBeløp: number;
        rettsligGrunnlag: RettsligGrunnlag[];
    }[];
    rettsligGrunnlag: RettsligGrunnlag[];
};

export type Fakta = {
    perioder: Periode[];
};

export type _Error = {
    code: number;
    message: string;
};

export type BehandlingFaktaData = {
    body?: never;
    path: {
        behandlingId: string;
    };
    query?: never;
    url: '/api/v1/behandling/{behandlingId}/fakta';
};

export type BehandlingFaktaErrors = {
    /**
     * An unexpected error response.
     */
    default: _Error;
};

export type BehandlingFaktaError = BehandlingFaktaErrors[keyof BehandlingFaktaErrors];

export type BehandlingFaktaResponses = {
    /**
     * The request has succeeded.
     */
    200: Fakta;
};

export type BehandlingFaktaResponse = BehandlingFaktaResponses[keyof BehandlingFaktaResponses];
