// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zBestemmelseEllerGrunnlag = z.object({
    nøkkel: z.string(),
    beskrivelse: z.string(),
});

export const zRettsligGrunnlag = z.object({
    bestemmelse: zBestemmelseEllerGrunnlag,
    grunnlag: zBestemmelseEllerGrunnlag,
});

export const zPeriode = z.object({
    id: z.string(),
    fom: z.iso.datetime(),
    tom: z.iso.datetime(),
    feilutbetaltBeløp: z.int(),
    splittbarePerioder: z.array(
        z.object({
            id: z.string(),
            fom: z.iso.datetime(),
            tom: z.iso.datetime(),
            feilutbetaltBeløp: z.int(),
            rettsligGrunnlag: z.array(zRettsligGrunnlag),
        })
    ),
    rettsligGrunnlag: z.array(zRettsligGrunnlag),
});

export const zFakta = z.object({
    perioder: z.array(zPeriode),
});

export const zError = z.object({
    code: z.int(),
    message: z.string(),
});

export const zBehandlingFaktaData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        behandlingId: z.string(),
    }),
    query: z.optional(z.never()),
});

/**
 * The request has succeeded.
 */
export const zBehandlingFaktaResponse = zFakta;
