name: Build&deploy to dev

on:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/navikt/familie-tilbake-frontend:${{ github.sha }}
  VERSION: familie-tilbake-frontend:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: yarn
          registry-url: "https://npm.pkg.github.com"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@5139682d94efc37792e6b54386b5b470a68a4737
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish Docker image
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_RELEASE: ${{ github.sha }}
        run: |
          yarn
          yarn build
          yarn test
          docker build . -t ${IMAGE}
          docker push ${IMAGE}
  deploy:
    if: github.event.pull_request.draft == false && github.actor != 'dependabot[bot]'
    name: Deploy to NAIS / GCP
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: build_n_deploy/naiserator/naiserator_dev_gcp.yaml
          VAR: VERSION=${{ env.VERSION }}
