name: Build&deploy to dev

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

env:
  IMAGE: ghcr.io/navikt/familie-tilbake-frontend:${{ github.sha }}
  VERSION: familie-tilbake-frontend:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@ab80d026d4753220c4243394c07c7d80f9638d06
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish Docker image
        run: |
          yarn
          yarn build
          yarn test
          docker build . -t ${IMAGE}
          docker push ${IMAGE}
  deploy:
    if: github.event.pull_request.draft == false && github.actor != 'dependabot[bot]'
    name: Deploy to NAIS / GCP
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: build_n_deploy/naiserator/naiserator_dev_gcp.yaml
          VAR: VERSION=${{ env.VERSION }}
